#line 2 "lex.msg2yy.cc"

#line 4 "lex.msg2yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer msg2yy_create_buffer
#define yy_delete_buffer msg2yy_delete_buffer
#define yy_flex_debug msg2yy_flex_debug
#define yy_init_buffer msg2yy_init_buffer
#define yy_flush_buffer msg2yy_flush_buffer
#define yy_load_buffer_state msg2yy_load_buffer_state
#define yy_switch_to_buffer msg2yy_switch_to_buffer
#define yyin msg2yyin
#define yyleng msg2yyleng
#define yylex msg2yylex
#define yylineno msg2yylineno
#define yyout msg2yyout
#define yyrestart msg2yyrestart
#define yytext msg2yytext
#define yywrap msg2yywrap
#define yyalloc msg2yyalloc
#define yyrealloc msg2yyrealloc
#define yyfree msg2yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE msg2yyrestart(msg2yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int msg2yyleng;

extern FILE *msg2yyin, *msg2yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up msg2yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up msg2yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via msg2yyrestart()), so that the user can continue scanning by
	 * just pointing msg2yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when msg2yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int msg2yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow msg2yywrap()'s to do buffer switches
 * instead of setting up a fresh msg2yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void msg2yyrestart (FILE *input_file  );
void msg2yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE msg2yy_create_buffer (FILE *file,int size  );
void msg2yy_delete_buffer (YY_BUFFER_STATE b  );
void msg2yy_flush_buffer (YY_BUFFER_STATE b  );
void msg2yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void msg2yypop_buffer_state (void );

static void msg2yyensure_buffer_stack (void );
static void msg2yy_load_buffer_state (void );
static void msg2yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER msg2yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE msg2yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE msg2yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE msg2yy_scan_bytes (yyconst char *bytes,int len  );

void *msg2yyalloc (yy_size_t  );
void *msg2yyrealloc (void *,yy_size_t  );
void msg2yyfree (void *  );

#define yy_new_buffer msg2yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        msg2yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            msg2yy_create_buffer(msg2yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        msg2yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            msg2yy_create_buffer(msg2yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *msg2yyin = (FILE *) 0, *msg2yyout = (FILE *) 0;

typedef int yy_state_type;

extern int msg2yylineno;

int msg2yylineno = 1;

extern char *msg2yytext;
#define yytext_ptr msg2yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up msg2yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	msg2yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[219] =
    {   0,
        0,    0,    0,    0,    0,    0,   82,   80,   79,   79,
       59,   31,   62,   71,   61,   80,   46,   47,   69,   67,
       43,   68,   52,   70,   26,   26,   44,   42,   72,   45,
       73,   53,   54,   25,   48,   49,   66,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   50,   60,   51,   63,   80,   41,   40,   40,
       41,   36,   32,   37,   81,   75,   58,   57,    0,   29,
        1,    0,   26,    0,    0,   55,   64,   76,   74,   77,
       65,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   38,   56,    0,   39,   36,   35,
       33,   34,   30,    0,    0,   28,   27,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   18,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   78,
        0,   29,   25,   15,   16,   25,   25,   25,    9,   25,
       25,   25,   19,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   23,   25,   25,    7,   25,   25,   25,   24,
       25,   25,   25,   25,   25,   25,   25,   17,   25,   25,
       25,   25,   25,   20,   25,   14,   25,   25,   25,    6,
       25,   25,   22,    4,   25,   25,   25,   10,    5,   25,

       25,   25,   25,   25,   11,   25,   25,   25,   25,   12,
       21,    3,    2,   25,   25,    8,   13,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   28,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       31,   32,   33,   34,   29,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   29,   51,   52,   53,   54,   29,   29,   55,
       56,   29,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   61,    1,    1,    1,
       62,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   63,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    5,    5,
        1,    2,    1,    1,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[226] =
    {   0,
        0,    0,   62,   64,   65,   66,  280,  281,  281,  281,
      256,  281,  272,  281,  269,    0,  281,  281,  281,  281,
      281,  281,   54,  259,   60,   64,  255,  281,   52,  251,
       61,  281,  281,    0,  281,  281,  281,  237,  223,   45,
      222,   38,   46,  222,  220,  229,   59,   61,  228,   58,
      215,  217,  207,  205,  281,  281,  201,  281,  281,  281,
      202,    0,  281,  281,   99,  281,  281,  281,  251,   88,
      281,   91,  101,  113,    0,  281,  281,  281,  281,  281,
      281,    0,  207,  209,  222,  221,  209,  200,  199,  199,
      205,  211,  196,  200,  195,  199,  197,  207,  194,  207,

      192,  189,  185,  186,  281,  281,  175,  281,    0,  281,
      281,  281,  281,  120,   95,  106,    0,  183,  189,  183,
      181,  178,  195,  183,  190,  176,  181,    0,  185,  173,
      185,  186,  177,  171,  182,  168,   87,  179,  174,  281,
      118,  124,  165,    0,    0,  163,  162,  167,    0,  164,
      172,  172,    0,  174,  156,  158,  167,  166,  155,  150,
      154,  164,    0,  159,  164,    0,  148,  158,  158,    0,
      143,  153,  143,  156,  138,  139,  141,    0,  147,  134,
      138,  148,  138,    0,  131,    0,  143,  146,  136,    0,
      126,  132,    0,    0,  138,  123,  121,    0,    0,  137,

      134,  129,  115,  124,    0,  104,   95,   85,   79,    0,
        0,    0,    0,   52,   49,    0,    0,  281,  143,  148,
      153,  155,  160,  165,   73
    } ;

static yyconst flex_int16_t yy_def[226] =
    {   0,
      218,    1,  219,  219,  220,  220,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  221,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  222,  218,  218,  218,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  223,  218,  218,  224,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  225,  218,  218,  218,  218,  218,
      218,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  218,  218,  218,  218,  223,  218,
      218,  218,  218,  218,  218,  218,  225,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  218,
      218,  218,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,    0,  218,  218,
      218,  218,  218,  218,  218
    } ;

static yyconst flex_int16_t yy_nxt[345] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   34,   34,   34,
       35,    8,   36,   37,   38,   39,   40,   41,   42,   43,
       34,   34,   44,   34,   34,   45,   46,   47,   34,   48,
       49,   50,   51,   52,   34,   34,   53,   54,   55,   56,
        8,    8,   57,   59,   60,   59,   60,   63,   63,   64,
       64,   70,   70,   77,   78,   72,  117,   73,   73,   72,
       91,   73,   73,   80,   81,   89,   85,   74,   92,   75,
       86,   74,   90,   96,   87,   98,   65,   65,   74,  101,

      217,  111,   74,  112,  216,   70,   70,   97,   70,   70,
      102,   99,  116,  116,   75,  114,   72,  215,   73,   73,
       61,  214,   61,  116,  116,  115,  114,  115,   74,  161,
      116,  116,  141,  213,  141,  142,  142,  142,  142,   74,
      162,  142,  142,   58,   58,   58,   58,   58,   62,   62,
       62,   62,   62,   69,   69,  212,   69,   69,   82,   82,
      109,  211,  109,  109,  109,  110,  110,  110,  110,  110,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,

      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  143,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  113,
      108,  107,  106,  105,  104,  103,  100,   95,   94,   93,
       88,   84,   83,   79,   76,   71,   68,   67,   66,  218,
        7,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218
    } ;

static yyconst flex_int16_t yy_chk[345] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    5,    6,    5,
        6,   23,   23,   29,   29,   25,  225,   25,   25,   26,
       43,   26,   26,   31,   31,   42,   40,   25,   43,   25,
       40,   26,   42,   47,   40,   48,    5,    6,   25,   50,

      215,   65,   26,   65,  214,   70,   70,   47,   72,   72,
       50,   48,  115,  115,   25,   70,   73,  209,   73,   73,
        3,  208,    4,  116,  116,   74,   70,   74,   73,  137,
       74,   74,  114,  207,  114,  141,  141,  114,  114,   73,
      137,  142,  142,  219,  219,  219,  219,  219,  220,  220,
      220,  220,  220,  221,  221,  206,  221,  221,  222,  222,
      223,  204,  223,  223,  223,  224,  224,  224,  224,  224,
      203,  202,  201,  200,  197,  196,  195,  192,  191,  189,
      188,  187,  185,  183,  182,  181,  180,  179,  177,  176,
      175,  174,  173,  172,  171,  169,  168,  167,  165,  164,

      162,  161,  160,  159,  158,  157,  156,  155,  154,  152,
      151,  150,  148,  147,  146,  143,  139,  138,  136,  135,
      134,  133,  132,  131,  130,  129,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  107,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   90,   89,   88,   87,   86,   85,   84,   83,   69,
       61,   57,   54,   53,   52,   51,   49,   46,   45,   44,
       41,   39,   38,   30,   27,   24,   15,   13,   11,    7,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int msg2yy_flex_debug;
int msg2yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *msg2yytext;
#line 1 "msg2.lex"
/*==================================================
 * File: msg2.lex
 *
 *  Lexical analyser for OMNeT++ MSG-2.
 *
 *  Author: Andras Varga
 *
 ==================================================*/
/*--------------------------------------------------------------*
  Copyright (C) 1992,2005 Andras Varga

  This file is distributed WITHOUT ANY WARRANTY. See the file
  `license' for details on this and other legal matters.
*--------------------------------------------------------------*/
/*
 * MSG-2 reserved words:
 *    non-component:   cplusplus
 *    component:       struct message class noncobject enum
 *    inheritance:     extends
 *    field types:     char short int long double unsigned
 *    field modifiers: abstract readonly
 */


/* the following option keeps isatty() out */
#line 40 "msg2.lex"
#include <string.h>
#include "nedyydefs.h"
#include "nedexception.h"
#include "msg2.tab.hh"

#define yylloc msg2yylloc
extern YYSTYPE yylval;
extern YYLTYPE yylloc;

// wrap symbols to allow several .lex files coexist
#define comment     msgcomment
#define countChars  msgcount
#define extendCount msgextendCount

void comment();
void countChars();
void extendCount();

#define TEXTBUF_LEN 1024
static char textbuf[TEXTBUF_LEN];

USING_NAMESPACE

#line 669 "lex.msg2yy.cc"

#define INITIAL 0
#define cplusplusbody 1
#define stringliteral 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int msg2yylex_destroy (void );

int msg2yyget_debug (void );

void msg2yyset_debug (int debug_flag  );

YY_EXTRA_TYPE msg2yyget_extra (void );

void msg2yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *msg2yyget_in (void );

void msg2yyset_in  (FILE * in_str  );

FILE *msg2yyget_out (void );

void msg2yyset_out  (FILE * out_str  );

int msg2yyget_leng (void );

char *msg2yyget_text (void );

int msg2yyget_lineno (void );

void msg2yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int msg2yywrap (void );
#else
extern int msg2yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( msg2yytext, msg2yyleng, 1, msg2yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( msg2yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( msg2yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, msg2yyin))==0 && ferror(msg2yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(msg2yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int msg2yylex (void);

#define YY_DECL int msg2yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after msg2yytext and msg2yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 65 "msg2.lex"

#line 855 "lex.msg2yy.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! msg2yyin )
			msg2yyin = stdin;

		if ( ! msg2yyout )
			msg2yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			msg2yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				msg2yy_create_buffer(msg2yyin,YY_BUF_SIZE );
		}

		msg2yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of msg2yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 219 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 218 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "msg2.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "msg2.lex"
{ countChars(); return NAMESPACE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "msg2.lex"
{ countChars(); return CPLUSPLUS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 70 "msg2.lex"
{ countChars(); return STRUCT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 71 "msg2.lex"
{ countChars(); return MESSAGE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "msg2.lex"
{ countChars(); return PACKET; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 73 "msg2.lex"
{ countChars(); return CLASS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 74 "msg2.lex"
{ countChars(); return NONCOBJECT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 75 "msg2.lex"
{ countChars(); return ENUM; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 76 "msg2.lex"
{ countChars(); return EXTENDS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 77 "msg2.lex"
{ countChars(); return ABSTRACT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 78 "msg2.lex"
{ countChars(); return READONLY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 79 "msg2.lex"
{ countChars(); return PROPERTIES; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 80 "msg2.lex"
{ countChars(); return FIELDS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 82 "msg2.lex"
{ countChars(); return BOOLTYPE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 83 "msg2.lex"
{ countChars(); return CHARTYPE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 84 "msg2.lex"
{ countChars(); return SHORTTYPE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 85 "msg2.lex"
{ countChars(); return INTTYPE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 86 "msg2.lex"
{ countChars(); return LONGTYPE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 87 "msg2.lex"
{ countChars(); return DOUBLETYPE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 88 "msg2.lex"
{ countChars(); return UNSIGNED_; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 89 "msg2.lex"
{ countChars(); return STRINGTYPE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 90 "msg2.lex"
{ countChars(); return TRUE_; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 91 "msg2.lex"
{ countChars(); return FALSE_; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 93 "msg2.lex"
{ countChars(); return NAME; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 94 "msg2.lex"
{ countChars(); return INTCONSTANT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 95 "msg2.lex"
{ countChars(); return INTCONSTANT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 "msg2.lex"
{ countChars(); return REALCONSTANT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "msg2.lex"
{ countChars(); return REALCONSTANT; }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 98 "msg2.lex"
{ countChars(); return CHARCONSTANT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 100 "msg2.lex"
{ countChars(); BEGIN(stringliteral); }
	YY_BREAK

case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 102 "msg2.lex"
{ BEGIN(INITIAL); throw NEDException("unterminated string literal (append backslash to line for multi-line strings)"); /* NOTE: BEGIN(INITIAL) is important, otherwise parsing of the next file (!) will start from the <stringliteral> state! */ }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 103 "msg2.lex"
{ extendCount(); /* line continuation */ }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 104 "msg2.lex"
{ extendCount(); /* qouted quote */ }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 105 "msg2.lex"
{ extendCount(); /* qouted char */ }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 106 "msg2.lex"
{ extendCount(); /* character inside string literal */ }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 107 "msg2.lex"
{ extendCount(); BEGIN(INITIAL); return STRINGCONSTANT; /* closing quote */ }
	YY_BREAK

case 38:
YY_RULE_SETUP
#line 110 "msg2.lex"
{ countChars(); BEGIN(cplusplusbody); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 111 "msg2.lex"
{ extendCount(); BEGIN(INITIAL); return CPLUSPLUSBODY; }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 112 "msg2.lex"
{ extendCount(); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "msg2.lex"
{ extendCount(); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 115 "msg2.lex"
{ countChars(); return ';'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 116 "msg2.lex"
{ countChars(); return ','; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 117 "msg2.lex"
{ countChars(); return ':'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 118 "msg2.lex"
{ countChars(); return '='; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 119 "msg2.lex"
{ countChars(); return '('; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 120 "msg2.lex"
{ countChars(); return ')'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 121 "msg2.lex"
{ countChars(); return '['; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 122 "msg2.lex"
{ countChars(); return ']'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 123 "msg2.lex"
{ countChars(); return '{'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 124 "msg2.lex"
{ countChars(); return '}'; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 125 "msg2.lex"
{ countChars(); return '.'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 126 "msg2.lex"
{ countChars(); return '?'; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 127 "msg2.lex"
{ countChars(); return '@'; }
	YY_BREAK
/* XXX are the next ones really needed? */
case 55:
YY_RULE_SETUP
#line 131 "msg2.lex"
{ countChars(); return DOUBLECOLON; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 132 "msg2.lex"
{ countChars(); return OR; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 133 "msg2.lex"
{ countChars(); return AND; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 134 "msg2.lex"
{ countChars(); return XOR; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 135 "msg2.lex"
{ countChars(); return NOT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 137 "msg2.lex"
{ countChars(); return BIN_OR; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 138 "msg2.lex"
{ countChars(); return BIN_AND; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 139 "msg2.lex"
{ countChars(); return BIN_XOR; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 140 "msg2.lex"
{ countChars(); return BIN_COMPL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 141 "msg2.lex"
{ countChars(); return SHIFT_LEFT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 142 "msg2.lex"
{ countChars(); return SHIFT_RIGHT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 144 "msg2.lex"
{ countChars(); return '^'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 145 "msg2.lex"
{ countChars(); return '+'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 146 "msg2.lex"
{ countChars(); return '-'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 147 "msg2.lex"
{ countChars(); return '*'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 148 "msg2.lex"
{ countChars(); return '/'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 149 "msg2.lex"
{ countChars(); return '%'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 150 "msg2.lex"
{ countChars(); return '<'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 151 "msg2.lex"
{ countChars(); return '>'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 153 "msg2.lex"
{ countChars(); return EQ; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 154 "msg2.lex"
{ countChars(); return NE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 155 "msg2.lex"
{ countChars(); return LE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 156 "msg2.lex"
{ countChars(); return GE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 158 "msg2.lex"
{ /* UTF-8 BOM mark, ignore */ }
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 159 "msg2.lex"
{ countChars(); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 160 "msg2.lex"
{ countChars(); return INVALID_CHAR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 162 "msg2.lex"
ECHO;
	YY_BREAK
#line 1347 "lex.msg2yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(cplusplusbody):
case YY_STATE_EOF(stringliteral):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed msg2yyin at a new source and called
			 * msg2yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = msg2yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( msg2yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * msg2yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of msg2yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					msg2yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			msg2yyrestart(msg2yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) msg2yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 219 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 219 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 218);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up msg2yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					msg2yyrestart(msg2yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( msg2yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve msg2yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void msg2yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        msg2yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            msg2yy_create_buffer(msg2yyin,YY_BUF_SIZE );
	}

	msg2yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	msg2yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void msg2yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		msg2yypop_buffer_state();
	 *		msg2yypush_buffer_state(new_buffer);
     */
	msg2yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	msg2yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (msg2yywrap()) processing, but the only time this flag
	 * is looked at is after msg2yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void msg2yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	msg2yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE msg2yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) msg2yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in msg2yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) msg2yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in msg2yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	msg2yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with msg2yy_create_buffer()
 * 
 */
    void msg2yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		msg2yyfree((void *) b->yy_ch_buf  );

	msg2yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a msg2yyrestart() or at EOF.
 */
    static void msg2yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	msg2yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then msg2yy_init_buffer was _probably_
     * called from msg2yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void msg2yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		msg2yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void msg2yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	msg2yyensure_buffer_stack();

	/* This block is copied from msg2yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from msg2yy_switch_to_buffer. */
	msg2yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void msg2yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	msg2yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		msg2yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void msg2yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)msg2yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in msg2yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)msg2yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in msg2yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE msg2yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) msg2yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in msg2yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	msg2yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to msg2yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       msg2yy_scan_bytes() instead.
 */
YY_BUFFER_STATE msg2yy_scan_string (yyconst char * yystr )
{
    
	return msg2yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to msg2yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE msg2yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) msg2yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in msg2yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = msg2yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in msg2yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up msg2yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		msg2yytext[msg2yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = msg2yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		msg2yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int msg2yyget_lineno  (void)
{
        
    return msg2yylineno;
}

/** Get the input stream.
 * 
 */
FILE *msg2yyget_in  (void)
{
        return msg2yyin;
}

/** Get the output stream.
 * 
 */
FILE *msg2yyget_out  (void)
{
        return msg2yyout;
}

/** Get the length of the current token.
 * 
 */
int msg2yyget_leng  (void)
{
        return msg2yyleng;
}

/** Get the current token.
 * 
 */

char *msg2yyget_text  (void)
{
        return msg2yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void msg2yyset_lineno (int  line_number )
{
    
    msg2yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see msg2yy_switch_to_buffer
 */
void msg2yyset_in (FILE *  in_str )
{
        msg2yyin = in_str ;
}

void msg2yyset_out (FILE *  out_str )
{
        msg2yyout = out_str ;
}

int msg2yyget_debug  (void)
{
        return msg2yy_flex_debug;
}

void msg2yyset_debug (int  bdebug )
{
        msg2yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from msg2yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    msg2yyin = stdin;
    msg2yyout = stdout;
#else
    msg2yyin = (FILE *) 0;
    msg2yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * msg2yylex_init()
     */
    return 0;
}

/* msg2yylex_destroy is for both reentrant and non-reentrant scanners. */
int msg2yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		msg2yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		msg2yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	msg2yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * msg2yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *msg2yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *msg2yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void msg2yyfree (void * ptr )
{
	free( (char *) ptr );	/* see msg2yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 162 "msg2.lex"



int msg2yywrap()
{
     return 1;
}

/*
 * - discards all remaining characters of a line of
 *   text from the inputstream.
 * - the characters are read with the input() and
 *   unput() functions.
 * - input() is sometimes called yyinput()...
 */
#ifdef __cplusplus
#define input  yyinput
#endif

/* the following #define is needed for broken flex versions */
#define yytext_ptr msg2yytext

void comment()
{
    int c;
    while ((c = input())!='\n' && c!=0 && c!=EOF);
    if (c=='\n') unput(c);
}

/*
 * - counts the line and column number of the current token in `pos'
 * - keeps a record of the complete current line in `textbuf[]'
 * - msg2yytext[] is the current token passed by (f)lex
 */
static void _count(bool updateprevpos)
{
    static int textbuflen;
    int i;

    /* printf("DBG: countChars(): prev=%d,%d  pos=%d,%d msg2yytext=>>%s<<\n",
           prevpos.li, prevpos.co, pos.li, pos.co, msg2yytext);
    */

    /* init textbuf */
    if (pos.li==1 && pos.co==0) {
        textbuf[0]='\0'; textbuflen=0;
    }

    if (updateprevpos) {
        prevpos = pos;
    }
    for (i = 0; msg2yytext[i] != '\0'; i++) {
        if (msg2yytext[i] == '\n') {
            pos.co = 0;
            pos.li++;
            textbuflen=0; textbuf[0]='\0';
        } else if (msg2yytext[i] == '\t')
            pos.co += 8 - (pos.co % 8);
        else
            pos.co++;
        if (msg2yytext[i] != '\n') {
            if (textbuflen < TEXTBUF_LEN-5) {
                textbuf[textbuflen++]=msg2yytext[i]; textbuf[textbuflen]='\0';
            }
            else if (textbuflen == TEXTBUF_LEN-5) {
                strcpy(textbuf+textbuflen, "...");
                textbuflen++;
            } else {
                /* line too long -- ignore */
            }
        }
    }
    /* printf("li=%d co=%d\n", pos.li, pos.co); good for debugging... */
    yylloc.first_line   = prevpos.li;
    yylloc.first_column = prevpos.co;
    yylloc.last_line    = pos.li;
    yylloc.last_column  = pos.co;
}

void countChars()
{
    _count(true);
}

void extendCount()
{
    _count(false);
}



