#line 2 "lex.ned1yy.cc"

#line 4 "lex.ned1yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ned1yy_create_buffer
#define yy_delete_buffer ned1yy_delete_buffer
#define yy_flex_debug ned1yy_flex_debug
#define yy_init_buffer ned1yy_init_buffer
#define yy_flush_buffer ned1yy_flush_buffer
#define yy_load_buffer_state ned1yy_load_buffer_state
#define yy_switch_to_buffer ned1yy_switch_to_buffer
#define yyin ned1yyin
#define yyleng ned1yyleng
#define yylex ned1yylex
#define yylineno ned1yylineno
#define yyout ned1yyout
#define yyrestart ned1yyrestart
#define yytext ned1yytext
#define yywrap ned1yywrap
#define yyalloc ned1yyalloc
#define yyrealloc ned1yyrealloc
#define yyfree ned1yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ned1yyrestart(ned1yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int ned1yyleng;

extern FILE *ned1yyin, *ned1yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ned1yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ned1yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ned1yyrestart()), so that the user can continue scanning by
	 * just pointing ned1yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ned1yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int ned1yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ned1yywrap()'s to do buffer switches
 * instead of setting up a fresh ned1yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ned1yyrestart (FILE *input_file  );
void ned1yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ned1yy_create_buffer (FILE *file,int size  );
void ned1yy_delete_buffer (YY_BUFFER_STATE b  );
void ned1yy_flush_buffer (YY_BUFFER_STATE b  );
void ned1yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void ned1yypop_buffer_state (void );

static void ned1yyensure_buffer_stack (void );
static void ned1yy_load_buffer_state (void );
static void ned1yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ned1yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ned1yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ned1yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ned1yy_scan_bytes (yyconst char *bytes,int len  );

void *ned1yyalloc (yy_size_t  );
void *ned1yyrealloc (void *,yy_size_t  );
void ned1yyfree (void *  );

#define yy_new_buffer ned1yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ned1yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ned1yy_create_buffer(ned1yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ned1yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ned1yy_create_buffer(ned1yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *ned1yyin = (FILE *) 0, *ned1yyout = (FILE *) 0;

typedef int yy_state_type;

extern int ned1yylineno;

int ned1yylineno = 1;

extern char *ned1yytext;
#define yytext_ptr ned1yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ned1yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ned1yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 121
#define YY_END_OF_BUFFER 122
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[379] =
    {   0,
        0,    0,    0,    0,    0,    0,  122,  120,  119,  119,
       99,   72,  102,  111,  101,  120,   88,   89,  109,  107,
       85,  108,   94,  110,   67,   67,   86,   84,  114,   87,
      116,   95,   66,   90,   91,  106,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   92,  100,   93,  103,  120,   82,
       81,   81,   82,   77,   73,   78,  121,  113,   98,   97,
        0,   83,    2,   34,   70,    1,    0,   67,    0,    0,
        0,  104,  115,  112,  117,  105,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,    9,   66,   66,

       66,   66,   66,   66,   66,   37,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   30,   66,   66,   66,   66,
       66,   66,   66,   66,   36,   66,   66,   66,   79,   96,
        0,   80,   77,   76,   74,   75,   71,   32,   35,    0,
        0,   69,   68,   33,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,    8,   66,   66,   25,   66,   66,   59,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   12,   66,   66,   66,   66,   66,   66,   66,   44,
      118,    0,   70,   66,   66,   66,   43,   66,   57,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   51,   66,   66,   66,   66,   66,   66,   66,
       66,   31,   60,   66,   66,   66,   66,   66,   66,   26,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   10,
       66,   66,   66,   66,   66,   66,   49,   66,   15,   66,
       66,   63,   66,   66,   66,   66,   66,   66,   66,   64,
       66,   11,   66,   23,   66,   38,   14,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   58,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   61,   66,   21,   66,   66,   66,   66,   53,

       66,    3,   66,    5,   66,   66,   66,   66,   66,   66,
       66,    6,   16,   42,   47,   66,   66,   40,   66,   66,
       45,    7,   66,   66,   66,   29,   66,   66,   66,   66,
       52,   66,   48,    4,   39,   66,   41,   66,   66,   66,
       66,   66,   55,   13,   66,   66,   65,   66,   66,   66,
       66,   66,   66,   66,   66,   56,   66,   62,   66,   46,
       66,   18,   66,   17,   24,   66,   66,   66,   66,   66,
       19,   20,   50,   22,   54,   27,   28,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   26,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   28,
       30,   31,   32,   33,   28,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   28,   50,   51,   52,   53,   28,   54,   55,
       56,   57,   58,   59,   60,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   62,    1,    1,    1,
       63,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   64,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    5,    5,    1,
        2,    1,    1,    4,    4,    4,    4,    4,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[386] =
    {   0,
        0,    0,   63,   65,   66,   67,  439,  440,  440,  440,
      415,  440,  431,  440,  428,    0,  440,  440,  440,  422,
      440,  419,   57,  416,   61,   65,  440,  440,   63,  409,
       70,  440,    0,  440,  440,  440,   54,  383,   59,   71,
       65,   76,  396,   75,   54,   79,   88,   81,   61,  391,
       90,   85,  381,  381,  368,  366,  440,  440,  362,  440,
      440,  440,  363,    0,  440,  440,  134,  440,  440,  440,
      413,  440,  397,  404,  111,  440,  126,  132,  139,    0,
      404,  440,  440,  440,  440,  440,    0,  367,  104,  369,
      382,  381,  367,  368,  360,  366,  359,  356,  109,  358,

      355,  361,  367,  354,  351,    0,  353,  127,  357,  353,
      348,  361,  345,  119,  350,    0,  343,  344,  345,   48,
      344,  110,  341,  355,    0,  336,  337,  342,  440,  440,
      323,  440,    0,  440,  440,  440,  440,  440,  440,  150,
      153,  155,    0,  440,  333,  346,  331,  337,  128,  330,
      130,  327,  345,  344,  328,  341,  144,  329,  326,  335,
      321,  326,    0,  332,  321,  440,  330,  314,    0,  328,
      325,  313,  310,  308,  320,  324,  321,  338,  323,  307,
      318,    0,  304,  304,  314,  140,  305,  312,  307,  311,
      440,  166,  168,  297,  295,  289,    0,  297,    0,  292,

      304,  289,  289,  289,  282,  292,  291,  294,  286,  285,
      294,  289,    0,  280,  282,  290,  290,  275,  275,  269,
      271,    0,    0,  288,  276,  272,  281,  270,  267,  440,
      270,  277,  266,  261,  267,  263,  263,  273,  260,    0,
      267,  258,  271,  252,  254,  264,    0,  265,    0,  251,
      265,    0,  264,  259,  262,  245,  257,  241,  246,    0,
      254,    0,  239,  247,  236,    0,    0,  247,  248,  235,
      248,  248,  240,  243,  230,  232,    0,  240,  238,  236,
      223,  237,  226,  236,  235,  222,  231,  223,  215,  221,
      213,  208,    0,  216,    0,  209,  207,  211,  208,    0,

      201,    0,  219,    0,  212,  211,  211,  217,  200,  199,
      205,    0,    0,    0,    0,  196,  210,    0,  195,  196,
        0,    0,  203,  191,  205,    0,  195,  196,  192,  194,
        0,  200,    0,    0,    0,  199,    0,  198,  193,  178,
      188,  195,    0,    0,  183,  179,    0,  191,  190,  177,
      188,  174,  188,  173,  176,    0,  170,    0,  147,    0,
      147,    0,  145,    0,    0,  136,  110,  102,   55,   40,
        0,    0,    0,    0,    0,    0,    0,  440,  195,  200,
      205,  207,  212,  217,   70
    } ;

static yyconst flex_int16_t yy_def[386] =
    {   0,
      378,    1,  379,  379,  380,  380,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  381,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  382,  378,  378,  378,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  383,  378,  378,  384,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  385,
      378,  378,  378,  378,  378,  378,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  378,  378,
      378,  378,  383,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  385,  378,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  378,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      378,  378,  378,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  378,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,    0,  378,  378,
      378,  378,  378,  378,  378
    } ;

static yyconst flex_int16_t yy_nxt[505] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   33,   33,   33,   34,
        8,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       33,   44,   33,   33,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   33,   54,   33,   33,   55,   56,   57,
       58,    8,    8,   59,   61,   62,   61,   62,   65,   65,
       66,   66,   74,  143,   75,   75,   77,   81,   78,   78,
       77,  181,   78,   78,   82,   83,  182,   79,   88,   80,
      377,   79,   85,   86,  118,  109,   67,   67,   79,   91,

       89,  110,   79,   92,   95,  376,   93,   94,   96,  102,
      119,   99,   97,  106,  100,   80,  111,  103,   98,  101,
      107,  108,   63,  104,   63,  113,  112,  116,   75,   75,
      121,  122,  125,  117,  126,  114,  135,  140,  136,  146,
      115,  123,  124,   75,   75,  157,  166,   77,  140,   78,
       78,  141,  375,  141,  175,  184,  142,  142,   79,  147,
      374,  158,  192,  167,  192,  176,  185,  193,  193,   79,
      142,  142,  142,  142,  198,  168,  201,  199,  169,  208,
      202,  237,  209,  193,  193,  193,  193,  373,  372,  210,
      211,  371,  238,  370,  212,   60,   60,   60,   60,   60,

       64,   64,   64,   64,   64,   71,   71,  369,   71,   71,
       87,   87,  133,  368,  133,  133,  133,  134,  134,  134,
      134,  134,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,

      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  207,  206,  205,  204,  203,
      200,  197,  196,  195,  194,  191,  190,  189,  188,  187,
      186,  183,  180,  179,  178,  177,  174,  173,  172,  171,

      170,  165,  164,  163,  162,  161,  160,  159,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  145,  144,  139,
      138,  137,  132,  131,  130,  129,  128,  127,  120,  105,
       90,   84,   76,   73,   72,   70,   69,   68,  378,    7,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378
    } ;

static yyconst flex_int16_t yy_chk[505] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    4,    4,    5,    6,
        5,    6,   23,  385,   23,   23,   25,   29,   25,   25,
       26,  120,   26,   26,   29,   29,  120,   25,   37,   25,
      370,   26,   31,   31,   49,   45,    5,    6,   25,   39,

       37,   45,   26,   39,   40,  369,   39,   39,   40,   42,
       49,   41,   40,   44,   41,   25,   46,   42,   40,   41,
       44,   44,    3,   42,    4,   47,   46,   48,   75,   75,
       51,   51,   52,   48,   52,   47,   67,   75,   67,   89,
       47,   51,   51,   77,   77,   99,  108,   78,   75,   78,
       78,   79,  368,   79,  114,  122,   79,   79,   78,   89,
      367,   99,  140,  108,  140,  114,  122,  140,  140,   78,
      141,  141,  142,  142,  149,  108,  151,  149,  108,  157,
      151,  186,  157,  192,  192,  193,  193,  366,  363,  157,
      157,  361,  186,  359,  157,  379,  379,  379,  379,  379,

      380,  380,  380,  380,  380,  381,  381,  357,  381,  381,
      382,  382,  383,  355,  383,  383,  383,  384,  384,  384,
      384,  384,  354,  353,  352,  351,  350,  349,  348,  346,
      345,  342,  341,  340,  339,  338,  336,  332,  330,  329,
      328,  327,  325,  324,  323,  320,  319,  317,  316,  311,
      310,  309,  308,  307,  306,  305,  303,  301,  299,  298,
      297,  296,  294,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  265,  264,  263,
      261,  259,  258,  257,  256,  255,  254,  253,  251,  250,

      248,  246,  245,  244,  243,  242,  241,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  229,  228,  227,  226,
      225,  224,  221,  220,  219,  218,  217,  216,  215,  214,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  198,  196,  195,  194,  190,  189,  188,
      187,  185,  184,  183,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  168,  167,  165,  164,
      162,  161,  160,  159,  158,  156,  155,  154,  153,  152,
      150,  148,  147,  146,  145,  131,  128,  127,  126,  124,
      123,  121,  119,  118,  117,  115,  113,  112,  111,  110,

      109,  107,  105,  104,  103,  102,  101,  100,   98,   97,
       96,   95,   94,   93,   92,   91,   90,   88,   81,   74,
       73,   71,   63,   59,   56,   55,   54,   53,   50,   43,
       38,   30,   24,   22,   20,   15,   13,   11,    7,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ned1yy_flex_debug;
int ned1yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ned1yytext;
#line 1 "ned1.lex"
/*==================================================
 * File: ned1.lex
 *
 *  Lexical analyser for OMNeT++ NED-1.
 *
 *  Author: Andras Varga
 *
 ==================================================*/
/*--------------------------------------------------------------*
  Copyright (C) 1992,2005 Andras Varga

  This file is distributed WITHOUT ANY WARRANTY. See the file
  `license' for details on this and other legal matters.
*--------------------------------------------------------------*/


/* the following option keeps isatty() out */
#line 31 "ned1.lex"
#include <string.h>
#include "nedyydefs.h"
#include "nedexception.h"
#include "ned1.tab.hh"

#define yylloc ned1yylloc
extern YYSTYPE yylval;
extern YYLTYPE yylloc;

// wrap symbols to allow several .lex files coexist
#define comment     ned1comment
#define countChars  ned1count
#define extendCount ned1extendCount

void comment();
void countChars();
void extendCount();

#define TEXTBUF_LEN 1024
static char textbuf[TEXTBUF_LEN];

USING_NAMESPACE

#line 748 "lex.ned1yy.cc"

#define INITIAL 0
#define cplusplusbody 1
#define stringliteral 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ned1yylex_destroy (void );

int ned1yyget_debug (void );

void ned1yyset_debug (int debug_flag  );

YY_EXTRA_TYPE ned1yyget_extra (void );

void ned1yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *ned1yyget_in (void );

void ned1yyset_in  (FILE * in_str  );

FILE *ned1yyget_out (void );

void ned1yyset_out  (FILE * out_str  );

int ned1yyget_leng (void );

char *ned1yyget_text (void );

int ned1yyget_lineno (void );

void ned1yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ned1yywrap (void );
#else
extern int ned1yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( ned1yytext, ned1yyleng, 1, ned1yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ned1yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ned1yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ned1yyin))==0 && ferror(ned1yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ned1yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ned1yylex (void);

#define YY_DECL int ned1yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ned1yytext and ned1yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 56 "ned1.lex"

#line 934 "lex.ned1yy.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ned1yyin )
			ned1yyin = stdin;

		if ( ! ned1yyout )
			ned1yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ned1yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ned1yy_create_buffer(ned1yyin,YY_BUF_SIZE );
		}

		ned1yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ned1yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 379 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 378 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "ned1.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "ned1.lex"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 "ned1.lex"
{ countChars(); return INCLUDE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 61 "ned1.lex"
{ countChars(); return NETWORK; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 62 "ned1.lex"
{ countChars(); return MODULE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 63 "ned1.lex"
{ countChars(); return SIMPLE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "ned1.lex"
{ countChars(); return CHANNEL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "ned1.lex"
{ countChars(); return FOR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "ned1.lex"
{ countChars(); return DO; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "ned1.lex"
{ countChars(); return TRUE_; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "ned1.lex"
{ countChars(); return FALSE_; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 "ned1.lex"
{ countChars(); return REF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 70 "ned1.lex"
{ countChars(); return ANCESTOR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 71 "ned1.lex"
{ countChars(); return INPUT_; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 72 "ned1.lex"
{ countChars(); return CONSTDECL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 73 "ned1.lex"
{ countChars(); return SIZEOF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 74 "ned1.lex"
{ countChars(); return ENDSIMPLE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 75 "ned1.lex"
{ countChars(); return ENDMODULE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 76 "ned1.lex"
{ countChars(); return ENDCHANNEL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 77 "ned1.lex"
{ countChars(); return ENDNETWORK; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 78 "ned1.lex"
{ countChars(); return ENDFOR; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "ned1.lex"
{ countChars(); return PARAMETERS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 80 "ned1.lex"
{ countChars(); return GATES; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 81 "ned1.lex"
{ countChars(); return GATESIZES; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "ned1.lex"
{ countChars(); return IN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 83 "ned1.lex"
{ countChars(); return OUT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 84 "ned1.lex"
{ countChars(); return SUBMODULES; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 85 "ned1.lex"
{ countChars(); return CONNECTIONS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 86 "ned1.lex"
{ countChars(); return DISPLAY; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 87 "ned1.lex"
{ countChars(); return ON; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 88 "ned1.lex"
{ countChars(); return LIKE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 89 "ned1.lex"
{ countChars(); return RIGHT_ARROW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 90 "ned1.lex"
{ countChars(); return LEFT_ARROW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 91 "ned1.lex"
{ countChars(); return TO; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 92 "ned1.lex"
{ countChars(); return TO; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 93 "ned1.lex"
{ countChars(); return TO; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 94 "ned1.lex"
{ countChars(); return IF; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 95 "ned1.lex"
{ countChars(); return SUBMODINDEX; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 96 "ned1.lex"
{ countChars(); return NOCHECK; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 97 "ned1.lex"
{ countChars(); return XMLDOC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "ned1.lex"
{ countChars(); return NUMERICTYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "ned1.lex"
{ countChars(); return STRINGTYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 101 "ned1.lex"
{ countChars(); return BOOLTYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "ned1.lex"
{ countChars(); return XMLTYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "ned1.lex"
{ countChars(); return ANYTYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "ned1.lex"
{ countChars(); return CPLUSPLUS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 106 "ned1.lex"
{ countChars(); return STRUCT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 107 "ned1.lex"
{ countChars(); return MESSAGE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 108 "ned1.lex"
{ countChars(); return CLASS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 109 "ned1.lex"
{ countChars(); return NONCOBJECT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 110 "ned1.lex"
{ countChars(); return ENUM; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 111 "ned1.lex"
{ countChars(); return EXTENDS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 112 "ned1.lex"
{ countChars(); return FIELDS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "ned1.lex"
{ countChars(); return PROPERTIES; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 114 "ned1.lex"
{ countChars(); return ABSTRACT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 115 "ned1.lex"
{ countChars(); return READONLY; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 117 "ned1.lex"
{ countChars(); return CHARTYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 118 "ned1.lex"
{ countChars(); return SHORTTYPE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 119 "ned1.lex"
{ countChars(); return INTTYPE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 120 "ned1.lex"
{ countChars(); return LONGTYPE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 121 "ned1.lex"
{ countChars(); return DOUBLETYPE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 122 "ned1.lex"
{ countChars(); return UNSIGNED_; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 124 "ned1.lex"
{ countChars(); return CHANATTRNAME; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 125 "ned1.lex"
{ countChars(); return CHANATTRNAME; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 126 "ned1.lex"
{ countChars(); return CHANATTRNAME; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 128 "ned1.lex"
{ countChars(); return NAME; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 129 "ned1.lex"
{ countChars(); return INTCONSTANT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 130 "ned1.lex"
{ countChars(); return INTCONSTANT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 131 "ned1.lex"
{ countChars(); return REALCONSTANT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 132 "ned1.lex"
{ countChars(); return REALCONSTANT; }
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 133 "ned1.lex"
{ countChars(); return CHARCONSTANT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 135 "ned1.lex"
{ countChars(); BEGIN(stringliteral); }
	YY_BREAK

case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 137 "ned1.lex"
{ BEGIN(INITIAL); throw NEDException("unterminated string literal (append backslash to line for multi-line strings)"); /* NOTE: BEGIN(INITIAL) is important, otherwise parsing of the next file (!) will start from the <stringliteral> state! */ }
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 138 "ned1.lex"
{ extendCount(); /* line continuation */ }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "ned1.lex"
{ extendCount(); /* qouted quote */ }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 140 "ned1.lex"
{ extendCount(); /* qouted char */ }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 141 "ned1.lex"
{ extendCount(); /* character inside string literal */ }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 142 "ned1.lex"
{ extendCount(); BEGIN(INITIAL); return STRINGCONSTANT; /* closing quote */ }
	YY_BREAK

case 79:
YY_RULE_SETUP
#line 145 "ned1.lex"
{ countChars(); BEGIN(cplusplusbody); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 146 "ned1.lex"
{ extendCount(); BEGIN(INITIAL); return CPLUSPLUSBODY; }
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 147 "ned1.lex"
{ extendCount(); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 148 "ned1.lex"
{ extendCount(); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 150 "ned1.lex"
{ countChars(); return PLUSPLUS; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 152 "ned1.lex"
{ countChars(); return ';'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 153 "ned1.lex"
{ countChars(); return ','; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 154 "ned1.lex"
{ countChars(); return ':'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 155 "ned1.lex"
{ countChars(); return '='; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 156 "ned1.lex"
{ countChars(); return '('; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 157 "ned1.lex"
{ countChars(); return ')'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 158 "ned1.lex"
{ countChars(); return '['; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 159 "ned1.lex"
{ countChars(); return ']'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 160 "ned1.lex"
{ countChars(); return '{'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 161 "ned1.lex"
{ countChars(); return '}'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 162 "ned1.lex"
{ countChars(); return '.'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 163 "ned1.lex"
{ countChars(); return '?'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 165 "ned1.lex"
{ countChars(); return OR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 166 "ned1.lex"
{ countChars(); return AND; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 167 "ned1.lex"
{ countChars(); return XOR; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 168 "ned1.lex"
{ countChars(); return NOT; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 170 "ned1.lex"
{ countChars(); return BIN_OR; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 171 "ned1.lex"
{ countChars(); return BIN_AND; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 172 "ned1.lex"
{ countChars(); return BIN_XOR; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 173 "ned1.lex"
{ countChars(); return BIN_COMPL; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 174 "ned1.lex"
{ countChars(); return SHIFT_LEFT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 175 "ned1.lex"
{ countChars(); return SHIFT_RIGHT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 177 "ned1.lex"
{ countChars(); return '^'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 178 "ned1.lex"
{ countChars(); return '+'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 179 "ned1.lex"
{ countChars(); return '-'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 180 "ned1.lex"
{ countChars(); return '*'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 181 "ned1.lex"
{ countChars(); return '/'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 182 "ned1.lex"
{ countChars(); return '%'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 184 "ned1.lex"
{ countChars(); return EQ; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 185 "ned1.lex"
{ countChars(); return NE; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 186 "ned1.lex"
{ countChars(); return LS; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 187 "ned1.lex"
{ countChars(); return LE; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 188 "ned1.lex"
{ countChars(); return GT; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 189 "ned1.lex"
{ countChars(); return GE; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 191 "ned1.lex"
{ /* UTF-8 BOM mark, ignore */ }
	YY_BREAK
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 192 "ned1.lex"
{ countChars(); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 193 "ned1.lex"
{ countChars(); return INVALID_CHAR; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 195 "ned1.lex"
ECHO;
	YY_BREAK
#line 1625 "lex.ned1yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(cplusplusbody):
case YY_STATE_EOF(stringliteral):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ned1yyin at a new source and called
			 * ned1yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ned1yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ned1yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ned1yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of ned1yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ned1yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ned1yyrestart(ned1yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ned1yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 379 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 379 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 378);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up ned1yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ned1yyrestart(ned1yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ned1yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ned1yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ned1yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ned1yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ned1yy_create_buffer(ned1yyin,YY_BUF_SIZE );
	}

	ned1yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	ned1yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ned1yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ned1yypop_buffer_state();
	 *		ned1yypush_buffer_state(new_buffer);
     */
	ned1yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ned1yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ned1yywrap()) processing, but the only time this flag
	 * is looked at is after ned1yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ned1yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ned1yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ned1yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ned1yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ned1yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ned1yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ned1yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ned1yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ned1yy_create_buffer()
 * 
 */
    void ned1yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ned1yyfree((void *) b->yy_ch_buf  );

	ned1yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ned1yyrestart() or at EOF.
 */
    static void ned1yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ned1yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ned1yy_init_buffer was _probably_
     * called from ned1yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ned1yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ned1yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ned1yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ned1yyensure_buffer_stack();

	/* This block is copied from ned1yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ned1yy_switch_to_buffer. */
	ned1yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ned1yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ned1yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ned1yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ned1yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ned1yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ned1yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ned1yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ned1yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ned1yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ned1yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ned1yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ned1yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ned1yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ned1yy_scan_bytes() instead.
 */
YY_BUFFER_STATE ned1yy_scan_string (yyconst char * yystr )
{
    
	return ned1yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ned1yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ned1yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ned1yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ned1yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ned1yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ned1yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ned1yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ned1yytext[ned1yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = ned1yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ned1yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ned1yyget_lineno  (void)
{
        
    return ned1yylineno;
}

/** Get the input stream.
 * 
 */
FILE *ned1yyget_in  (void)
{
        return ned1yyin;
}

/** Get the output stream.
 * 
 */
FILE *ned1yyget_out  (void)
{
        return ned1yyout;
}

/** Get the length of the current token.
 * 
 */
int ned1yyget_leng  (void)
{
        return ned1yyleng;
}

/** Get the current token.
 * 
 */

char *ned1yyget_text  (void)
{
        return ned1yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ned1yyset_lineno (int  line_number )
{
    
    ned1yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ned1yy_switch_to_buffer
 */
void ned1yyset_in (FILE *  in_str )
{
        ned1yyin = in_str ;
}

void ned1yyset_out (FILE *  out_str )
{
        ned1yyout = out_str ;
}

int ned1yyget_debug  (void)
{
        return ned1yy_flex_debug;
}

void ned1yyset_debug (int  bdebug )
{
        ned1yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ned1yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ned1yyin = stdin;
    ned1yyout = stdout;
#else
    ned1yyin = (FILE *) 0;
    ned1yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ned1yylex_init()
     */
    return 0;
}

/* ned1yylex_destroy is for both reentrant and non-reentrant scanners. */
int ned1yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ned1yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ned1yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	ned1yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ned1yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ned1yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ned1yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ned1yyfree (void * ptr )
{
	free( (char *) ptr );	/* see ned1yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 195 "ned1.lex"



int ned1yywrap()
{
     return 1;
}

/*
 * - discards all remaining characters of a line of
 *   text from the inputstream.
 * - the characters are read with the input() and
 *   unput() functions.
 * - input() is sometimes called yyinput()...
 */
#ifdef __cplusplus
#define input  yyinput
#endif

/* the following #define is needed for broken flex versions */
#define yytext_ptr ned1yytext

void comment()
{
    int c;
    while ((c = input())!='\n' && c!=0 && c!=EOF);
    if (c=='\n') unput(c);
}

/*
 * - counts the line and column number of the current token in `pos'
 * - keeps a record of the complete current line in `textbuf[]'
 * - ned1yytext[] is the current token passed by (f)lex
 */
static void _count(bool updateprevpos)
{
    static int textbuflen;
    int i;

    /* printf("DBG: countChars(): prev=%d,%d  pos=%d,%d ned1yytext=>>%s<<\n",
           prevpos.li, prevpos.co, pos.li, pos.co, ned1yytext);
    */

    /* init textbuf */
    if (pos.li==1 && pos.co==0) {
        textbuf[0]='\0'; textbuflen=0;
    }

    if (updateprevpos) {
        prevpos = pos;
    }
    for (i = 0; ned1yytext[i] != '\0'; i++) {
        if (ned1yytext[i] == '\n') {
            pos.co = 0;
            pos.li++;
            textbuflen=0; textbuf[0]='\0';
        } else if (ned1yytext[i] == '\t')
            pos.co += 8 - (pos.co % 8);
        else
            pos.co++;
        if (ned1yytext[i] != '\n') {
            if (textbuflen < TEXTBUF_LEN-5) {
                textbuf[textbuflen++]=ned1yytext[i]; textbuf[textbuflen]='\0';
            }
            else if (textbuflen == TEXTBUF_LEN-5) {
                strcpy(textbuf+textbuflen, "...");
                textbuflen++;
            } else {
                /* line too long -- ignore */
            }
        }
    }
    /* printf("li=%d co=%d\n", pos.li, pos.co); good for debugging... */
    yylloc.first_line   = prevpos.li;
    yylloc.first_column = prevpos.co;
    yylloc.last_line    = pos.li;
    yylloc.last_column  = pos.co;
}

void countChars()
{
    _count(true);
}

void extendCount()
{
    _count(false);
}



