
#ifndef _H_SIRIUS_CONST
#define _H_SIRIUS_CONST

#define SIRIUS_MPI_INIT 1
#define SIRIUS_MPI_FINALIZE 2

#define SIRIUS_MPI_SEND 4
#define SIRIUS_MPI_RECV 16

#define SIRIUS_MPI_BARRIER 64
#define SIRIUS_MPI_ALLREDUCE 65

#define SIRIUS_MPI_COMM_SELF 1
#define SIRIUS_MPI_COMM_WORLD 2

#define SIRIUS_MPI_INTEGER 1
#define SIRIUS_MPI_DOUBLE 2

#define SIRIUS_MPI_SUM 1
#define SIRIUS_MPI_MAX 16
#define SIRIUS_MPI_MIN 17

#endif
