#sst --lib-path=../.libs/ test_txntrace4.py --model-options="--configfile=../hbm_legacy_8h.cfg --tracefile=../traces/seq_hbm.seq02" 
#sst --lib-path=../.libs/ test_txntrace4.py --model-options="--configfile=../hbm_pseudo_8h.cfg --tracefile=../traces/seq_hbm.seq02" 
sst --lib-path=../.libs/ test_newarch.py --model-options="--configfile=../hbm_pseudo_1h.cfg --tracefile=../traces/seq_hbm.seq02" 
#sst --lib-path=../.libs/ test_newarch.py --model-options="--configfile=../hbm_legacy_8h.cfg --tracefile=../traces/seq_hbm.seq02" 
#sst --lib-path=../.libs/ test_statTest1.py --model-options="--configfile=../ddr4_verimem.cfg --tracefile=../traces/sst-CramSim-trace_verimem_6_W.trc"
