// Copyright 2009-2014 Sandia Corporation. Under the terms
// of Contract DE-AC04-94AL85000 with Sandia Corporation, the U.S.
// Government retains certain rights in this software.
//
// Copyright (c) 2009-2014, Sandia Corporation
// All rights reserved.
//
// This file is part of the SST software package. For license
// information, see the LICENSE file in the top level directory of the
// distribution.

#ifndef SST_OBERON_INSTRUCTION
#define SST_OBERON_INSTRUCTION

#define OBERON_INST_NOP 	0

#define OBERON_INST_PUSH_I64	1
#define OBERON_INST_POP_I64	2

#define OBERON_INST_PUSH_FP64	3
#define OBERON_INST_POP_FP64	4

#define OBERON_INST_PUSH_LIT_I64	5
#define OBERON_INST_PUSH_LIT_U32	6
#define OBERON_INST_PUSH_LIT_FP64	7

#define OBERON_INST_IADD	16
#define OBERON_INST_ISUB	17
#define OBERON_INST_IMUL	18
#define OBERON_INST_IDIV	19
#define OBERON_INST_IMOD	20
#define OBERON_INST_IPOW	21
#define OBERON_INST_ILOG10	22
#define OBERON_INST_ILN		23
#define OBERON_INST_ILOG2	24
#define OBERON_INST_IEXP	25

#define OBERON_INST_FP64ADD	64
#define OBERON_INST_FP64SUB	65
#define OBERON_INST_FP64MUL	66
#define OBERON_INST_FP64DIV	67
#define OBERON_INST_FP64MOD	68

#define OBERON_INST_CMP_I64LT	128
#define OBERON_INST_CMP_I64LTE	129
#define OBERON_INST_CMP_I64EQ	130
#define OBERON_INST_CMP_I64GTE	131
#define OBERON_INST_CMP_I64GT	132

#define OBERON_INST_CMP_FP64LT	256
#define OBERON_INST_CMP_FP64LTE	257
#define OBERON_INST_CMP_FP64EQ	258
#define OBERON_INST_CMP_FP64GTE	259
#define OBERON_INST_CMP_FP64GT	260

#define OBERON_INST_JUMP	512
#define OBERON_INST_JUMPREL	513
#define OBERON_INST_CJUMP_ZERO	514
#define OBERON_INST_CJUMP_NZERO 515
#define OBERON_INST_CRELJUMP_ZERO  516
#define OBERON_INST_CRELJUMP_NZERO 517

#define OBERON_INST_AND		1024
#define OBERON_INST_OR		1025
#define OBERON_INST_NOT		1026

#define OBERON_INST_HALT	65536
#define OBERON_INST_DUMP_MEM	65537

#define OBERON_INST_PRINT_I64	131072

#endif
