#ifndef SST_OBERON_INSTRUCTION
#define SST_OBERON_INSTRUCTION

#define OBERON_INST_NOP 	0

#define OBERON_INST_PUSH_I64	1
#define OBERON_INST_POP_I64	2

#define OBERON_INST_PUSH_FP64	3
#define OBERON_INST_POP_FP64	4

#define OBERON_INST_PUSH_LIT_I64	5
#define OBERON_INST_PUSH_LIT_U32	6
#define OBERON_INST_PUSH_LIT_FP64	7

#define OBERON_INST_IADD	16
#define OBERON_INST_ISUB	17
#define OBERON_INST_IMUL	18
#define OBERON_INST_IDIV	19
#define OBERON_INST_IMOD	20

#define OBERON_INST_HALT	65536
#define OBERON_INST_DUMP_MEM	65537

#endif
