
all:
	cd m5syscall && $(MAKE)
	cd runtime && $(MAKE)
	cd libc && $(MAKE)

install:
	cd m5syscall && $(MAKE) install
	cd runtime && $(MAKE) install
	cd libc && $(MAKE) install

clean:
	cd m5syscall && $(MAKE) clean
	cd runtime && $(MAKE) clean
	cd libc && $(MAKE) clean
