#!/bin/bash
CXX=$(sst-config --CXX)
ELEMENT_CXXFLAGS=$(sst-config --ELEMENT_CXXFLAGS)
ELEMENT_LDFLAGS=$(sst-config --ELEMENT_LDFLAGS)
INCLUDE_DIR=$(sst-config --includedir)
INCLUDE_DIR+="/sst/elements/hg"
SST_ELEMENT_LIBRARY_BUILDDIR=$(sst-config SST_ELEMENT_LIBRARY SST_ELEMENT_LIBRARY_BUILDDIR)
SST_ELEMENT_LIBRARY_BUILDDIR+="/src"

COMPILE="$CXX $ELEMENT_CXXFLAGS -I$INCLUDE_DIR -I$SST_ELEMENT_LIBRARY_BUILDDIR -g -O0 -c testme.cc"
echo "$COMPILE"
$COMPILE
LINK="$CXX $ELEMENT_LDFLAGS -o testme testme.o"
echo "$LINK"
$LINK
