#!/bin/bash

MERCURY_TESTS_DIR=$(sst-config SST_ELEMENT_TESTS mercury)
cd "$MERCURY_TESTS_DIR" || exit
CXX=$(sst-config --CXX)
ELEMENT_CXXFLAGS=$(sst-config --ELEMENT_CXXFLAGS)
INCLUDE_DIR=$(sst-config --includedir)
MERCURY_INCLUDE_DIR=$(sst-config SST_ELEMENT_SOURCE mercury)
SST_ELEMENT_LIBRARY_BUILDDIR=$(sst-config SST_ELEMENT_LIBRARY SST_ELEMENT_LIBRARY_BUILDDIR)
LIBTOOL=$SST_ELEMENT_LIBRARY_BUILDDIR
LIBTOOL+="/libtool"
SST_ELEMENT_LIBRARY_BUILDDIR+="/src"
MERCURY_TEST_DIR=$(sst-config SST_ELEMENT_TESTS mercury)

set -x

LT_COMPILE="$LIBTOOL --mode=compile --tag=CXX $CXX $ELEMENT_CXXFLAGS -I$INCLUDE_DIR -I$MERCURY_INCLUDE_DIR -I$SST_ELEMENT_LIBRARY_BUILDDIR -g -O0 -c testme.cc"
$LT_COMPILE

LT_LINK="$LIBTOOL --verbose --mode=link --tag=CXX $CXX -rpath $MERCURY_TEST_DIR -module -o testme.la testme.lo"
$LT_LINK

LT_INSTALL="$LIBTOOL --mode=install cp testme.la $MERCURY_TESTS_DIR"
$LT_INSTALL
