# Automatically generated by SST
import sst

# Define SST Program Options:
sst.setProgramOption("timebase", "1 ps")
sst.setProgramOption("stopAtCycle", "0 ns")

# Define the global parameter sets:
sst.addGlobalParams("ctrl_params_FireflyHades_6", {
    "ackVN" : "0",
    "matchDelay_ns" : "150",
    "nicsPerNode" : "1",
    "pqs.verboseLevel" : "0",
    "pqs.verboseMask" : "-1",
    "recvStateDelay_ps" : "0",
    "regRegionBaseDelay_ns" : "3000",
    "regRegionPerPageDelay_ns" : "100",
    "regRegionXoverLength" : "4096",
    "rendezvousVN" : "0",
    "rxMemcpyMod" : "firefly.LatencyMod",
    "rxMemcpyModParams.base" : "344ps",
    "rxSetupMod" : "firefly.LatencyMod",
    "rxSetupModParams.base" : "100ns",
    "sendAckDelay_ns" : "0",
    "sendStateDelay_ps" : "0",
    "shortMsgLength" : "12000",
    "txMemcpyMod" : "firefly.LatencyMod",
    "txMemcpyModParams.base" : "344ps",
    "txMemcpyModParams.op" : "Mult",
    "txSetupMod" : "firefly.LatencyMod",
    "txSetupModParams.base" : "130ns",
    "verboseLevel" : "0",
    "waitallStateDelay_ps" : "0",
    "waitanyStateDelay_ps" : "0",
})
sst.addGlobalParams("hr_router_1_params", {
    "flit_size" : "16B",
    "input_buf_size" : "14kB",
    "link_bw" : "25GB/s",
    "output_buf_size" : "14kB",
    "xbar_bw" : "40GB/s",
})
sst.addGlobalParams("loopback_params_HgJob_3", {
    "nicsPerNode" : "1",
    "numCores" : "1",
})
sst.addGlobalParams("params_BasicNicConfiguration_7", {
    "hostReadDelay_ns" : "200",
    "maxSendMachineQsize" : "100",
    "nic2host_lat" : "150ns",
    "num_vNics" : "1",
    "packetOverhead" : "0",
    "packetSize" : "2048B",
    "rxMatchDelay_ns" : "100",
    "txDelay_ns" : "50",
    "useSimpleMemoryModel" : "0",
})
sst.addGlobalParams("params_FireflyHades_6", {
    "functionSM.defaultEnterLatency" : "30000",
    "functionSM.defaultModule" : "firefly",
    "functionSM.defaultReturnLatency" : "30000",
    "functionSM.smallCollectiveSize" : "8",
    "functionSM.smallCollectiveVN" : "0",
    "functionSM.verboseLevel" : "0",
    "netMapName" : "Firefly0",
    "netMapSize" : "2",
    "numNodes" : "2",
})
sst.addGlobalParams("params_HgJob_3", {
    "jobId" : "0",
})
sst.addGlobalParams("params_LinkControl_5", {
    "input_buf_size" : "14kB",
    "job_id" : "0",
    "job_size" : "2",
    "link_bw" : "25 GB/s",
    "output_buf_size" : "14kB",
    "use_nid_remap" : "False",
})

# Define the SST Components:
comp_router = sst.Component("router", "merlin.hr_router")
comp_router.addParams({
     "num_ports" : "2",
     "id" : "0"
})
comp_router.addGlobalParamSet("hr_router_1_params")
comp_router.setCoordinates(0, 0, 0)
link_id_00000002 = sst.Link("link_id_00000002")
comp_router.addLink(link_id_00000002, "port0", "60 ns")
link_id_00000005 = sst.Link("link_id_00000005")
comp_router.addLink(link_id_00000005, "port1", "60 ns")
comp_router_subcomp_topology = comp_router.setSubComponent("topology", "merlin.singlerouter", 0)
comp_router_subcomp_topology.addParams({
     "num_ports" : "2"
})
comp_router_subcomp_topology.setCoordinates(0, 0, 0)
comp_nic0 = sst.Component("nic0", "firefly.nic")
comp_nic0.addParams({
     "nid" : "0"
})
comp_nic0.addGlobalParamSet("params_BasicNicConfiguration_7")
comp_nic0.setCoordinates(0, 0, 0)
link_id_00000000 = sst.Link("link_id_00000000")
comp_nic0.addLink(link_id_00000000, "core0", "1 ns")
comp_nic0_subcomp_rtrLink = comp_nic0.setSubComponent("rtrLink", "merlin.reorderlinkcontrol", 0)
comp_nic0_subcomp_rtrLink.setCoordinates(0, 0, 0)
comp_nic0_subcomp_rtrLink_subcomp_networkIF = comp_nic0_subcomp_rtrLink.setSubComponent("networkIF", "merlin.linkcontrol", 0)
comp_nic0_subcomp_rtrLink_subcomp_networkIF.addParams({
     "logical_nid" : "0"
})
comp_nic0_subcomp_rtrLink_subcomp_networkIF.addGlobalParamSet("params_LinkControl_5")
comp_nic0_subcomp_rtrLink_subcomp_networkIF.setCoordinates(0, 0, 0)
comp_nic0_subcomp_rtrLink_subcomp_networkIF.addLink(link_id_00000002, "rtr_port", "60 ns")
comp_loopBack0 = sst.Component("loopBack0", "firefly.loopBack")
comp_loopBack0.addParams({
     "numCores" : "1",
     "nicsPerNode" : "1"
})
comp_loopBack0.addGlobalParamSet("loopback_params_HgJob_3")
comp_loopBack0.setCoordinates(0, 0, 0)
link_id_00000001 = sst.Link("link_id_00000001")
comp_loopBack0.addLink(link_id_00000001, "nic0core0", "1 ns")
comp_hgnode0 = sst.Component("hgnode0", "hg.node")
comp_hgnode0.addParams({
     "eventsToSend" : "50",
     "eventSize" : "32"
})
comp_hgnode0.addGlobalParamSet("params_HgJob_3")
comp_hgnode0.setCoordinates(0, 0, 0)
comp_hgnode0_subcomp_OS = comp_hgnode0.setSubComponent("OS", "firefly.hades", 0)
comp_hgnode0_subcomp_OS.addParams({
     "netId" : "0",
     "netMapId" : "0",
     "coreId" : "0"
})
comp_hgnode0_subcomp_OS.addGlobalParamSet("params_FireflyHades_6")
comp_hgnode0_subcomp_OS.setCoordinates(0, 0, 0)
comp_hgnode0_subcomp_OS_subcomp_virtNic = comp_hgnode0_subcomp_OS.setSubComponent("virtNic", "firefly.VirtNic", 0)
comp_hgnode0_subcomp_OS_subcomp_virtNic.setCoordinates(0, 0, 0)
comp_hgnode0_subcomp_OS_subcomp_virtNic.addLink(link_id_00000000, "nic", "1 ns")
comp_hgnode0_subcomp_OS_subcomp_proto = comp_hgnode0_subcomp_OS.setSubComponent("proto", "firefly.CtrlMsgProto", 0)
comp_hgnode0_subcomp_OS_subcomp_proto.addParams({

})
comp_hgnode0_subcomp_OS_subcomp_proto.addGlobalParamSet("ctrl_params_FireflyHades_6")
comp_hgnode0_subcomp_OS_subcomp_proto.setCoordinates(0, 0, 0)
comp_hgnode0_subcomp_OS_subcomp_proto_subcomp_process = comp_hgnode0_subcomp_OS_subcomp_proto.setSubComponent("process", "firefly.ctrlMsg", 0)
comp_hgnode0_subcomp_OS_subcomp_proto_subcomp_process.addParams({

})
comp_hgnode0_subcomp_OS_subcomp_proto_subcomp_process.addGlobalParamSet("ctrl_params_FireflyHades_6")
comp_hgnode0_subcomp_OS_subcomp_proto_subcomp_process.setCoordinates(0, 0, 0)
comp_hgnode0_subcomp_OS_subcomp_proto_subcomp_process.addLink(link_id_00000001, "loop", "1 ns")
comp_nic1 = sst.Component("nic1", "firefly.nic")
comp_nic1.addParams({
     "nid" : "1"
})
comp_nic1.addGlobalParamSet("params_BasicNicConfiguration_7")
comp_nic1.setCoordinates(0, 0, 0)
link_id_00000003 = sst.Link("link_id_00000003")
comp_nic1.addLink(link_id_00000003, "core0", "1 ns")
comp_nic1_subcomp_rtrLink = comp_nic1.setSubComponent("rtrLink", "merlin.reorderlinkcontrol", 0)
comp_nic1_subcomp_rtrLink.setCoordinates(0, 0, 0)
comp_nic1_subcomp_rtrLink_subcomp_networkIF = comp_nic1_subcomp_rtrLink.setSubComponent("networkIF", "merlin.linkcontrol", 0)
comp_nic1_subcomp_rtrLink_subcomp_networkIF.addParams({
     "logical_nid" : "1"
})
comp_nic1_subcomp_rtrLink_subcomp_networkIF.addGlobalParamSet("params_LinkControl_5")
comp_nic1_subcomp_rtrLink_subcomp_networkIF.setCoordinates(0, 0, 0)
comp_nic1_subcomp_rtrLink_subcomp_networkIF.addLink(link_id_00000005, "rtr_port", "60 ns")
comp_loopBack1 = sst.Component("loopBack1", "firefly.loopBack")
comp_loopBack1.addParams({
     "numCores" : "1",
     "nicsPerNode" : "1"
})
comp_loopBack1.addGlobalParamSet("loopback_params_HgJob_3")
comp_loopBack1.setCoordinates(0, 0, 0)
link_id_00000004 = sst.Link("link_id_00000004")
comp_loopBack1.addLink(link_id_00000004, "nic0core0", "1 ns")
comp_hgnode1 = sst.Component("hgnode1", "hg.node")
comp_hgnode1.addParams({
     "eventsToSend" : "50",
     "eventSize" : "32"
})
comp_hgnode1.addGlobalParamSet("params_HgJob_3")
comp_hgnode1.setCoordinates(0, 0, 0)
comp_hgnode1_subcomp_OS = comp_hgnode1.setSubComponent("OS", "firefly.hades", 0)
comp_hgnode1_subcomp_OS.addParams({
     "netId" : "1",
     "netMapId" : "1",
     "coreId" : "0"
})
comp_hgnode1_subcomp_OS.addGlobalParamSet("params_FireflyHades_6")
comp_hgnode1_subcomp_OS.setCoordinates(0, 0, 0)
comp_hgnode1_subcomp_OS_subcomp_virtNic = comp_hgnode1_subcomp_OS.setSubComponent("virtNic", "firefly.VirtNic", 0)
comp_hgnode1_subcomp_OS_subcomp_virtNic.setCoordinates(0, 0, 0)
comp_hgnode1_subcomp_OS_subcomp_virtNic.addLink(link_id_00000003, "nic", "1 ns")
comp_hgnode1_subcomp_OS_subcomp_proto = comp_hgnode1_subcomp_OS.setSubComponent("proto", "firefly.CtrlMsgProto", 0)
comp_hgnode1_subcomp_OS_subcomp_proto.addParams({

})
comp_hgnode1_subcomp_OS_subcomp_proto.addGlobalParamSet("ctrl_params_FireflyHades_6")
comp_hgnode1_subcomp_OS_subcomp_proto.setCoordinates(0, 0, 0)
comp_hgnode1_subcomp_OS_subcomp_proto_subcomp_process = comp_hgnode1_subcomp_OS_subcomp_proto.setSubComponent("process", "firefly.ctrlMsg", 0)
comp_hgnode1_subcomp_OS_subcomp_proto_subcomp_process.addParams({

})
comp_hgnode1_subcomp_OS_subcomp_proto_subcomp_process.addGlobalParamSet("ctrl_params_FireflyHades_6")
comp_hgnode1_subcomp_OS_subcomp_proto_subcomp_process.setCoordinates(0, 0, 0)
comp_hgnode1_subcomp_OS_subcomp_proto_subcomp_process.addLink(link_id_00000004, "loop", "1 ns")
# Define SST Statistics Options:
sst.setStatisticOutput("sst.statOutputConsole")
# End of generated output.

