# Automatically generated by SST
import sst

# Define SST Program Options:
sst.setProgramOption("timebase", "1 ps")
sst.setProgramOption("stopAtCycle", "0 ns")

# Define the SST Components:
comp_rtr_G0R0 = sst.Component("rtr:G0R0", "merlin.hr_router")
comp_rtr_G0R0.addParams({
     "dragonfly:algorithm" : "adaptive-local",
     "dragonfly:intergroup_per_router" : "1",
     "num_peers" : "24",
     "output_buf_size" : "14KB",
     "router_radix" : "7",
     "num_vns" : "1",
     "dragonfly:routers_per_group" : "3",
     "num_ports" : "7",
     "flit_size" : "8B",
     "link_bw" : "12.5GB/s",
     "dragonfly:shape" : "",
     "dragonfly:intergroup_links" : "1",
     "link_lat" : "40ns",
     "topology" : "merlin.dragonfly2",
     "dragonfly:hosts_per_router" : "4",
     "output_latency" : "50ns",
     "xbar_bw" : "12.5GB/s",
     "dragonfly:num_groups" : "2",
     "input_buf_size" : "14KB",
     "input_latency" : "50ns",
     "debug" : "0",
     "id" : "0",
     "dragonfly:global_link_map" : "[0, -1, -1]"
})
comp_nic0 = sst.Component("nic0", "firefly.nic")
comp_nic0.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "0"
})
comp_loopBack0 = sst.Component("loopBack0", "firefly.loopBack")
comp_loopBack0.addParams({
     "numCores" : "1"
})
comp_nic0core0_EmberEP = sst.Component("nic0core0_EmberEP", "ember.EmberEngine")
comp_nic0core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "0",
     "hermesParams.netMapId" : "2",
     "hermesParams.netMapSize" : "24"
})
comp_nic1 = sst.Component("nic1", "firefly.nic")
comp_nic1.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "1"
})
comp_loopBack1 = sst.Component("loopBack1", "firefly.loopBack")
comp_loopBack1.addParams({
     "numCores" : "1"
})
comp_nic1core0_EmberEP = sst.Component("nic1core0_EmberEP", "ember.EmberEngine")
comp_nic1core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "1",
     "hermesParams.netMapId" : "8",
     "hermesParams.netMapSize" : "24"
})
comp_nic2 = sst.Component("nic2", "firefly.nic")
comp_nic2.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "2"
})
comp_loopBack2 = sst.Component("loopBack2", "firefly.loopBack")
comp_loopBack2.addParams({
     "numCores" : "1"
})
comp_nic2core0_EmberEP = sst.Component("nic2core0_EmberEP", "ember.EmberEngine")
comp_nic2core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "2",
     "hermesParams.netMapId" : "10",
     "hermesParams.netMapSize" : "24"
})
comp_nic3 = sst.Component("nic3", "firefly.nic")
comp_nic3.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "3"
})
comp_loopBack3 = sst.Component("loopBack3", "firefly.loopBack")
comp_loopBack3.addParams({
     "numCores" : "1"
})
comp_nic3core0_EmberEP = sst.Component("nic3core0_EmberEP", "ember.EmberEngine")
comp_nic3core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "3",
     "hermesParams.netMapId" : "7",
     "hermesParams.netMapSize" : "24"
})
comp_rtr_G0R1 = sst.Component("rtr:G0R1", "merlin.hr_router")
comp_rtr_G0R1.addParams({
     "dragonfly:algorithm" : "adaptive-local",
     "dragonfly:intergroup_per_router" : "1",
     "num_peers" : "24",
     "output_buf_size" : "14KB",
     "router_radix" : "7",
     "num_vns" : "1",
     "dragonfly:routers_per_group" : "3",
     "num_ports" : "7",
     "flit_size" : "8B",
     "link_bw" : "12.5GB/s",
     "dragonfly:shape" : "",
     "dragonfly:intergroup_links" : "1",
     "link_lat" : "40ns",
     "topology" : "merlin.dragonfly2",
     "dragonfly:hosts_per_router" : "4",
     "output_latency" : "50ns",
     "xbar_bw" : "12.5GB/s",
     "dragonfly:num_groups" : "2",
     "input_buf_size" : "14KB",
     "input_latency" : "50ns",
     "debug" : "0",
     "id" : "1"
})
comp_nic4 = sst.Component("nic4", "firefly.nic")
comp_nic4.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "4"
})
comp_loopBack4 = sst.Component("loopBack4", "firefly.loopBack")
comp_loopBack4.addParams({
     "numCores" : "1"
})
comp_nic4core0_EmberEP = sst.Component("nic4core0_EmberEP", "ember.EmberEngine")
comp_nic4core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "4",
     "hermesParams.netMapId" : "12",
     "hermesParams.netMapSize" : "24"
})
comp_nic5 = sst.Component("nic5", "firefly.nic")
comp_nic5.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "5"
})
comp_loopBack5 = sst.Component("loopBack5", "firefly.loopBack")
comp_loopBack5.addParams({
     "numCores" : "1"
})
comp_nic5core0_EmberEP = sst.Component("nic5core0_EmberEP", "ember.EmberEngine")
comp_nic5core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "5",
     "hermesParams.netMapId" : "1",
     "hermesParams.netMapSize" : "24"
})
comp_nic6 = sst.Component("nic6", "firefly.nic")
comp_nic6.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "6"
})
comp_loopBack6 = sst.Component("loopBack6", "firefly.loopBack")
comp_loopBack6.addParams({
     "numCores" : "1"
})
comp_nic6core0_EmberEP = sst.Component("nic6core0_EmberEP", "ember.EmberEngine")
comp_nic6core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "6",
     "hermesParams.netMapId" : "11",
     "hermesParams.netMapSize" : "24"
})
comp_nic7 = sst.Component("nic7", "firefly.nic")
comp_nic7.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "7"
})
comp_loopBack7 = sst.Component("loopBack7", "firefly.loopBack")
comp_loopBack7.addParams({
     "numCores" : "1"
})
comp_nic7core0_EmberEP = sst.Component("nic7core0_EmberEP", "ember.EmberEngine")
comp_nic7core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "7",
     "hermesParams.netMapId" : "18",
     "hermesParams.netMapSize" : "24"
})
comp_rtr_G0R2 = sst.Component("rtr:G0R2", "merlin.hr_router")
comp_rtr_G0R2.addParams({
     "dragonfly:algorithm" : "adaptive-local",
     "dragonfly:intergroup_per_router" : "1",
     "num_peers" : "24",
     "output_buf_size" : "14KB",
     "router_radix" : "7",
     "num_vns" : "1",
     "dragonfly:routers_per_group" : "3",
     "num_ports" : "7",
     "flit_size" : "8B",
     "link_bw" : "12.5GB/s",
     "dragonfly:shape" : "",
     "dragonfly:intergroup_links" : "1",
     "link_lat" : "40ns",
     "topology" : "merlin.dragonfly2",
     "dragonfly:hosts_per_router" : "4",
     "output_latency" : "50ns",
     "xbar_bw" : "12.5GB/s",
     "dragonfly:num_groups" : "2",
     "input_buf_size" : "14KB",
     "input_latency" : "50ns",
     "debug" : "0",
     "id" : "2"
})
comp_nic8 = sst.Component("nic8", "firefly.nic")
comp_nic8.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "8"
})
comp_loopBack8 = sst.Component("loopBack8", "firefly.loopBack")
comp_loopBack8.addParams({
     "numCores" : "1"
})
comp_nic8core0_EmberEP = sst.Component("nic8core0_EmberEP", "ember.EmberEngine")
comp_nic8core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "8",
     "hermesParams.netMapId" : "19",
     "hermesParams.netMapSize" : "24"
})
comp_nic9 = sst.Component("nic9", "firefly.nic")
comp_nic9.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "9"
})
comp_loopBack9 = sst.Component("loopBack9", "firefly.loopBack")
comp_loopBack9.addParams({
     "numCores" : "1"
})
comp_nic9core0_EmberEP = sst.Component("nic9core0_EmberEP", "ember.EmberEngine")
comp_nic9core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "9",
     "hermesParams.netMapId" : "9",
     "hermesParams.netMapSize" : "24"
})
comp_nic10 = sst.Component("nic10", "firefly.nic")
comp_nic10.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "10"
})
comp_loopBack10 = sst.Component("loopBack10", "firefly.loopBack")
comp_loopBack10.addParams({
     "numCores" : "1"
})
comp_nic10core0_EmberEP = sst.Component("nic10core0_EmberEP", "ember.EmberEngine")
comp_nic10core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "10",
     "hermesParams.netMapId" : "16",
     "hermesParams.netMapSize" : "24"
})
comp_nic11 = sst.Component("nic11", "firefly.nic")
comp_nic11.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "11"
})
comp_loopBack11 = sst.Component("loopBack11", "firefly.loopBack")
comp_loopBack11.addParams({
     "numCores" : "1"
})
comp_nic11core0_EmberEP = sst.Component("nic11core0_EmberEP", "ember.EmberEngine")
comp_nic11core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "11",
     "hermesParams.netMapId" : "13",
     "hermesParams.netMapSize" : "24"
})
comp_rtr_G1R0 = sst.Component("rtr:G1R0", "merlin.hr_router")
comp_rtr_G1R0.addParams({
     "dragonfly:algorithm" : "adaptive-local",
     "dragonfly:intergroup_per_router" : "1",
     "num_peers" : "24",
     "output_buf_size" : "14KB",
     "router_radix" : "7",
     "num_vns" : "1",
     "dragonfly:routers_per_group" : "3",
     "num_ports" : "7",
     "flit_size" : "8B",
     "link_bw" : "12.5GB/s",
     "dragonfly:shape" : "",
     "dragonfly:intergroup_links" : "1",
     "link_lat" : "40ns",
     "topology" : "merlin.dragonfly2",
     "dragonfly:hosts_per_router" : "4",
     "output_latency" : "50ns",
     "xbar_bw" : "12.5GB/s",
     "dragonfly:num_groups" : "2",
     "input_buf_size" : "14KB",
     "input_latency" : "50ns",
     "debug" : "0",
     "id" : "3"
})
comp_nic12 = sst.Component("nic12", "firefly.nic")
comp_nic12.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "12"
})
comp_loopBack12 = sst.Component("loopBack12", "firefly.loopBack")
comp_loopBack12.addParams({
     "numCores" : "1"
})
comp_nic12core0_EmberEP = sst.Component("nic12core0_EmberEP", "ember.EmberEngine")
comp_nic12core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "12",
     "hermesParams.netMapId" : "5",
     "hermesParams.netMapSize" : "24"
})
comp_nic13 = sst.Component("nic13", "firefly.nic")
comp_nic13.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "13"
})
comp_loopBack13 = sst.Component("loopBack13", "firefly.loopBack")
comp_loopBack13.addParams({
     "numCores" : "1"
})
comp_nic13core0_EmberEP = sst.Component("nic13core0_EmberEP", "ember.EmberEngine")
comp_nic13core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "13",
     "hermesParams.netMapId" : "22",
     "hermesParams.netMapSize" : "24"
})
comp_nic14 = sst.Component("nic14", "firefly.nic")
comp_nic14.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "14"
})
comp_loopBack14 = sst.Component("loopBack14", "firefly.loopBack")
comp_loopBack14.addParams({
     "numCores" : "1"
})
comp_nic14core0_EmberEP = sst.Component("nic14core0_EmberEP", "ember.EmberEngine")
comp_nic14core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "14",
     "hermesParams.netMapId" : "4",
     "hermesParams.netMapSize" : "24"
})
comp_nic15 = sst.Component("nic15", "firefly.nic")
comp_nic15.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "15"
})
comp_loopBack15 = sst.Component("loopBack15", "firefly.loopBack")
comp_loopBack15.addParams({
     "numCores" : "1"
})
comp_nic15core0_EmberEP = sst.Component("nic15core0_EmberEP", "ember.EmberEngine")
comp_nic15core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "15",
     "hermesParams.netMapId" : "23",
     "hermesParams.netMapSize" : "24"
})
comp_rtr_G1R1 = sst.Component("rtr:G1R1", "merlin.hr_router")
comp_rtr_G1R1.addParams({
     "dragonfly:algorithm" : "adaptive-local",
     "dragonfly:intergroup_per_router" : "1",
     "num_peers" : "24",
     "output_buf_size" : "14KB",
     "router_radix" : "7",
     "num_vns" : "1",
     "dragonfly:routers_per_group" : "3",
     "num_ports" : "7",
     "flit_size" : "8B",
     "link_bw" : "12.5GB/s",
     "dragonfly:shape" : "",
     "dragonfly:intergroup_links" : "1",
     "link_lat" : "40ns",
     "topology" : "merlin.dragonfly2",
     "dragonfly:hosts_per_router" : "4",
     "output_latency" : "50ns",
     "xbar_bw" : "12.5GB/s",
     "dragonfly:num_groups" : "2",
     "input_buf_size" : "14KB",
     "input_latency" : "50ns",
     "debug" : "0",
     "id" : "4"
})
comp_nic16 = sst.Component("nic16", "firefly.nic")
comp_nic16.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "16"
})
comp_loopBack16 = sst.Component("loopBack16", "firefly.loopBack")
comp_loopBack16.addParams({
     "numCores" : "1"
})
comp_nic16core0_EmberEP = sst.Component("nic16core0_EmberEP", "ember.EmberEngine")
comp_nic16core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "16",
     "hermesParams.netMapId" : "15",
     "hermesParams.netMapSize" : "24"
})
comp_nic17 = sst.Component("nic17", "firefly.nic")
comp_nic17.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "17"
})
comp_loopBack17 = sst.Component("loopBack17", "firefly.loopBack")
comp_loopBack17.addParams({
     "numCores" : "1"
})
comp_nic17core0_EmberEP = sst.Component("nic17core0_EmberEP", "ember.EmberEngine")
comp_nic17core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "17",
     "hermesParams.netMapId" : "20",
     "hermesParams.netMapSize" : "24"
})
comp_nic18 = sst.Component("nic18", "firefly.nic")
comp_nic18.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "18"
})
comp_loopBack18 = sst.Component("loopBack18", "firefly.loopBack")
comp_loopBack18.addParams({
     "numCores" : "1"
})
comp_nic18core0_EmberEP = sst.Component("nic18core0_EmberEP", "ember.EmberEngine")
comp_nic18core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "18",
     "hermesParams.netMapId" : "17",
     "hermesParams.netMapSize" : "24"
})
comp_nic19 = sst.Component("nic19", "firefly.nic")
comp_nic19.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "19"
})
comp_loopBack19 = sst.Component("loopBack19", "firefly.loopBack")
comp_loopBack19.addParams({
     "numCores" : "1"
})
comp_nic19core0_EmberEP = sst.Component("nic19core0_EmberEP", "ember.EmberEngine")
comp_nic19core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "19",
     "hermesParams.netMapId" : "6",
     "hermesParams.netMapSize" : "24"
})
comp_rtr_G1R2 = sst.Component("rtr:G1R2", "merlin.hr_router")
comp_rtr_G1R2.addParams({
     "dragonfly:algorithm" : "adaptive-local",
     "dragonfly:intergroup_per_router" : "1",
     "num_peers" : "24",
     "output_buf_size" : "14KB",
     "router_radix" : "7",
     "num_vns" : "1",
     "dragonfly:routers_per_group" : "3",
     "num_ports" : "7",
     "flit_size" : "8B",
     "link_bw" : "12.5GB/s",
     "dragonfly:shape" : "",
     "dragonfly:intergroup_links" : "1",
     "link_lat" : "40ns",
     "topology" : "merlin.dragonfly2",
     "dragonfly:hosts_per_router" : "4",
     "output_latency" : "50ns",
     "xbar_bw" : "12.5GB/s",
     "dragonfly:num_groups" : "2",
     "input_buf_size" : "14KB",
     "input_latency" : "50ns",
     "debug" : "0",
     "id" : "5"
})
comp_nic20 = sst.Component("nic20", "firefly.nic")
comp_nic20.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "20"
})
comp_loopBack20 = sst.Component("loopBack20", "firefly.loopBack")
comp_loopBack20.addParams({
     "numCores" : "1"
})
comp_nic20core0_EmberEP = sst.Component("nic20core0_EmberEP", "ember.EmberEngine")
comp_nic20core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "20",
     "hermesParams.netMapId" : "0",
     "hermesParams.netMapSize" : "24"
})
comp_nic21 = sst.Component("nic21", "firefly.nic")
comp_nic21.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "21"
})
comp_loopBack21 = sst.Component("loopBack21", "firefly.loopBack")
comp_loopBack21.addParams({
     "numCores" : "1"
})
comp_nic21core0_EmberEP = sst.Component("nic21core0_EmberEP", "ember.EmberEngine")
comp_nic21core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "21",
     "hermesParams.netMapId" : "3",
     "hermesParams.netMapSize" : "24"
})
comp_nic22 = sst.Component("nic22", "firefly.nic")
comp_nic22.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "22"
})
comp_loopBack22 = sst.Component("loopBack22", "firefly.loopBack")
comp_loopBack22.addParams({
     "numCores" : "1"
})
comp_nic22core0_EmberEP = sst.Component("nic22core0_EmberEP", "ember.EmberEngine")
comp_nic22core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "22",
     "hermesParams.netMapId" : "21",
     "hermesParams.netMapSize" : "24"
})
comp_nic23 = sst.Component("nic23", "firefly.nic")
comp_nic23.addParams({
     "link_bw" : "12.5GB/s",
     "nic2host_lat" : "150ns",
     "num_vNics" : "1",
     "packetSize" : "2048B",
     "module" : "merlin.reorderlinkcontrol",
     "rxMatchDelay_ns" : "100",
     "verboseLevel" : "0",
     "buffer_size" : "14KB",
     "txDelay_ns" : "50",
     "nid" : "23"
})
comp_loopBack23 = sst.Component("loopBack23", "firefly.loopBack")
comp_loopBack23.addParams({
     "numCores" : "1"
})
comp_nic23core0_EmberEP = sst.Component("nic23core0_EmberEP", "ember.EmberEngine")
comp_nic23core0_EmberEP.addParams({
     "motif1.spyplotmode" : "0",
     "hermesParams.functionSM.verboseLevel" : "0",
     "verbose" : "0",
     "hermesParams.ctrlMsg.rxMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.ctrlMsg.txSetupModParams.range.0" : "0-:130ns",
     "hermesParams.loadMap.0.len" : "2",
     "jobId" : "0",
     "hermesParams.ctrlMsg.matchDelay_ns" : "150",
     "hermesParams.ctrlMsg.regRegionBaseDelay_ns" : "3000",
     "hermesParams.nicModule" : "firefly.VirtNic",
     "motif0.api" : "HadesMP",
     "os.name" : "hermesParams",
     "hermesParams.ctrlMsg.txMemcpyModParams.range.0" : "0-:344ps",
     "hermesParams.verboseLevel" : "0",
     "motif1.api" : "HadesMP",
     "hermesParams.ctrlMsg.shortMsgLength" : "12000",
     "os.module" : "firefly.hades",
     "motif2.printStats" : "0",
     "motif0.spyplotmode" : "0",
     "motif2.spyplotmode" : "0",
     "motif1.name" : "ember.Halo3D26Motif",
     "hermesParams.ctrlMsg.txMemcpyMod" : "firefly.LatencyMod",
     "motif1.arg.ny" : "100",
     "motif1.arg.nx" : "100",
     "motif1.arg.nz" : "100",
     "hermesParams.ctrlMsg.verboseLevel" : "0",
     "hermesParams.ctrlMsg.txMemcpyModParams.op" : "Mult",
     "motif1.printStats" : "0",
     "motif1.arg.pez" : "2",
     "motif1.arg.pey" : "4",
     "motif1.arg.pex" : "3",
     "hermesParams.ctrlMsg.sendAckDelay_ns" : "0",
     "hermesParams.functionSM.defaultEnterLatency" : "30000",
     "hermesParams.ctrlMsg.rxMemcpyMod" : "firefly.LatencyMod",
     "motif2.name" : "ember.FiniMotif",
     "motif0.printStats" : "0",
     "hermesParams.ctrlMsg.txSetupMod" : "firefly.LatencyMod",
     "hermesParams.ctrlMsg.rxSetupMod" : "firefly.LatencyMod",
     "hermesParams.nicParams.verboseLevel" : "0",
     "hermesParams.functionSM.defaultReturnLatency" : "30000",
     "hermesParams.loadMap.0.start" : "0",
     "hermesParams.ctrlMsg.rxSetupModParams.range.0" : "0-:100ns",
     "motif0.name" : "ember.InitMotif",
     "motif_count" : "3",
     "api.0.module" : "firefly.hadesMP",
     "motif2.api" : "HadesMP",
     "hermesParams.ctrlMsg.regRegionPerPageDelay_ns" : "100",
     "hermesParams.mapType" : "random",
     "hermesParams.ctrlMsg.regRegionXoverLength" : "4096",
     "hermesParams.netId" : "23",
     "hermesParams.netMapId" : "14",
     "hermesParams.netMapSize" : "24"
})


# Define the SST Component Statistics Information
# Define SST Statistics Options:
sst.setStatisticLoadLevel(1)

# Define Component Statistics Information:
comp_rtr_G0R0.enableStatistics(["--ALLSTATS--"], {
     "type" : "sst.AccumulatorStatistic"
})
comp_rtr_G0R1.enableStatistics(["--ALLSTATS--"], {
     "type" : "sst.AccumulatorStatistic"
})
comp_rtr_G0R2.enableStatistics(["--ALLSTATS--"], {
     "type" : "sst.AccumulatorStatistic"
})
comp_rtr_G1R0.enableStatistics(["--ALLSTATS--"], {
     "type" : "sst.AccumulatorStatistic"
})
comp_rtr_G1R1.enableStatistics(["--ALLSTATS--"], {
     "type" : "sst.AccumulatorStatistic"
})
comp_rtr_G1R2.enableStatistics(["--ALLSTATS--"], {
     "type" : "sst.AccumulatorStatistic"
})


# Define SST Simulation Link Information
link_link_g0r0h0 = sst.Link("link_link_g0r0h0link_g0r0h0")
link_link_g0r0h0.connect( (comp_rtr_G0R0, "port0", "40000ps"), (comp_nic0, "rtr", "40000ps") )
link_nic0core0_Link = sst.Link("link_nic0core0_Linknic0core0_Link")
link_nic0core0_Link.connect( (comp_nic0core0_EmberEP, "nic", "150000ps"), (comp_nic0, "core0", "150000ps") )
link_loop0core0_Link = sst.Link("link_loop0core0_Linkloop0core0_Link")
link_loop0core0_Link.connect( (comp_nic0core0_EmberEP, "loop", "1000ps"), (comp_loopBack0, "core0", "1000ps") )
link_link_g0r0h1 = sst.Link("link_link_g0r0h1link_g0r0h1")
link_link_g0r0h1.connect( (comp_rtr_G0R0, "port1", "40000ps"), (comp_nic1, "rtr", "40000ps") )
link_nic1core0_Link = sst.Link("link_nic1core0_Linknic1core0_Link")
link_nic1core0_Link.connect( (comp_nic1core0_EmberEP, "nic", "150000ps"), (comp_nic1, "core0", "150000ps") )
link_loop1core0_Link = sst.Link("link_loop1core0_Linkloop1core0_Link")
link_loop1core0_Link.connect( (comp_nic1core0_EmberEP, "loop", "1000ps"), (comp_loopBack1, "core0", "1000ps") )
link_link_g0r0h2 = sst.Link("link_link_g0r0h2link_g0r0h2")
link_link_g0r0h2.connect( (comp_rtr_G0R0, "port2", "40000ps"), (comp_nic2, "rtr", "40000ps") )
link_nic2core0_Link = sst.Link("link_nic2core0_Linknic2core0_Link")
link_nic2core0_Link.connect( (comp_nic2core0_EmberEP, "nic", "150000ps"), (comp_nic2, "core0", "150000ps") )
link_loop2core0_Link = sst.Link("link_loop2core0_Linkloop2core0_Link")
link_loop2core0_Link.connect( (comp_nic2core0_EmberEP, "loop", "1000ps"), (comp_loopBack2, "core0", "1000ps") )
link_link_g0r0h3 = sst.Link("link_link_g0r0h3link_g0r0h3")
link_link_g0r0h3.connect( (comp_rtr_G0R0, "port3", "40000ps"), (comp_nic3, "rtr", "40000ps") )
link_nic3core0_Link = sst.Link("link_nic3core0_Linknic3core0_Link")
link_nic3core0_Link.connect( (comp_nic3core0_EmberEP, "nic", "150000ps"), (comp_nic3, "core0", "150000ps") )
link_loop3core0_Link = sst.Link("link_loop3core0_Linkloop3core0_Link")
link_loop3core0_Link.connect( (comp_nic3core0_EmberEP, "loop", "1000ps"), (comp_loopBack3, "core0", "1000ps") )
link_link_g0r0r1 = sst.Link("link_link_g0r0r1link_g0r0r1")
link_link_g0r0r1.connect( (comp_rtr_G0R0, "port4", "40000ps"), (comp_rtr_G0R1, "port4", "40000ps") )
link_link_g0r0r2 = sst.Link("link_link_g0r0r2link_g0r0r2")
link_link_g0r0r2.connect( (comp_rtr_G0R0, "port5", "40000ps"), (comp_rtr_G0R2, "port4", "40000ps") )
link_link_g0g1r0 = sst.Link("link_link_g0g1r0link_g0g1r0")
link_link_g0g1r0.connect( (comp_rtr_G0R0, "port6", "40000ps"), (comp_rtr_G1R0, "port6", "40000ps") )
link_link_g0r1h0 = sst.Link("link_link_g0r1h0link_g0r1h0")
link_link_g0r1h0.connect( (comp_rtr_G0R1, "port0", "40000ps"), (comp_nic4, "rtr", "40000ps") )
link_nic4core0_Link = sst.Link("link_nic4core0_Linknic4core0_Link")
link_nic4core0_Link.connect( (comp_nic4core0_EmberEP, "nic", "150000ps"), (comp_nic4, "core0", "150000ps") )
link_loop4core0_Link = sst.Link("link_loop4core0_Linkloop4core0_Link")
link_loop4core0_Link.connect( (comp_nic4core0_EmberEP, "loop", "1000ps"), (comp_loopBack4, "core0", "1000ps") )
link_link_g0r1h1 = sst.Link("link_link_g0r1h1link_g0r1h1")
link_link_g0r1h1.connect( (comp_rtr_G0R1, "port1", "40000ps"), (comp_nic5, "rtr", "40000ps") )
link_nic5core0_Link = sst.Link("link_nic5core0_Linknic5core0_Link")
link_nic5core0_Link.connect( (comp_nic5core0_EmberEP, "nic", "150000ps"), (comp_nic5, "core0", "150000ps") )
link_loop5core0_Link = sst.Link("link_loop5core0_Linkloop5core0_Link")
link_loop5core0_Link.connect( (comp_nic5core0_EmberEP, "loop", "1000ps"), (comp_loopBack5, "core0", "1000ps") )
link_link_g0r1h2 = sst.Link("link_link_g0r1h2link_g0r1h2")
link_link_g0r1h2.connect( (comp_rtr_G0R1, "port2", "40000ps"), (comp_nic6, "rtr", "40000ps") )
link_nic6core0_Link = sst.Link("link_nic6core0_Linknic6core0_Link")
link_nic6core0_Link.connect( (comp_nic6core0_EmberEP, "nic", "150000ps"), (comp_nic6, "core0", "150000ps") )
link_loop6core0_Link = sst.Link("link_loop6core0_Linkloop6core0_Link")
link_loop6core0_Link.connect( (comp_nic6core0_EmberEP, "loop", "1000ps"), (comp_loopBack6, "core0", "1000ps") )
link_link_g0r1h3 = sst.Link("link_link_g0r1h3link_g0r1h3")
link_link_g0r1h3.connect( (comp_rtr_G0R1, "port3", "40000ps"), (comp_nic7, "rtr", "40000ps") )
link_nic7core0_Link = sst.Link("link_nic7core0_Linknic7core0_Link")
link_nic7core0_Link.connect( (comp_nic7core0_EmberEP, "nic", "150000ps"), (comp_nic7, "core0", "150000ps") )
link_loop7core0_Link = sst.Link("link_loop7core0_Linkloop7core0_Link")
link_loop7core0_Link.connect( (comp_nic7core0_EmberEP, "loop", "1000ps"), (comp_loopBack7, "core0", "1000ps") )
link_link_g0r1r2 = sst.Link("link_link_g0r1r2link_g0r1r2")
link_link_g0r1r2.connect( (comp_rtr_G0R1, "port5", "40000ps"), (comp_rtr_G0R2, "port5", "40000ps") )
link_link_g0r2h0 = sst.Link("link_link_g0r2h0link_g0r2h0")
link_link_g0r2h0.connect( (comp_rtr_G0R2, "port0", "40000ps"), (comp_nic8, "rtr", "40000ps") )
link_nic8core0_Link = sst.Link("link_nic8core0_Linknic8core0_Link")
link_nic8core0_Link.connect( (comp_nic8core0_EmberEP, "nic", "150000ps"), (comp_nic8, "core0", "150000ps") )
link_loop8core0_Link = sst.Link("link_loop8core0_Linkloop8core0_Link")
link_loop8core0_Link.connect( (comp_nic8core0_EmberEP, "loop", "1000ps"), (comp_loopBack8, "core0", "1000ps") )
link_link_g0r2h1 = sst.Link("link_link_g0r2h1link_g0r2h1")
link_link_g0r2h1.connect( (comp_rtr_G0R2, "port1", "40000ps"), (comp_nic9, "rtr", "40000ps") )
link_nic9core0_Link = sst.Link("link_nic9core0_Linknic9core0_Link")
link_nic9core0_Link.connect( (comp_nic9core0_EmberEP, "nic", "150000ps"), (comp_nic9, "core0", "150000ps") )
link_loop9core0_Link = sst.Link("link_loop9core0_Linkloop9core0_Link")
link_loop9core0_Link.connect( (comp_nic9core0_EmberEP, "loop", "1000ps"), (comp_loopBack9, "core0", "1000ps") )
link_link_g0r2h2 = sst.Link("link_link_g0r2h2link_g0r2h2")
link_link_g0r2h2.connect( (comp_rtr_G0R2, "port2", "40000ps"), (comp_nic10, "rtr", "40000ps") )
link_nic10core0_Link = sst.Link("link_nic10core0_Linknic10core0_Link")
link_nic10core0_Link.connect( (comp_nic10core0_EmberEP, "nic", "150000ps"), (comp_nic10, "core0", "150000ps") )
link_loop10core0_Link = sst.Link("link_loop10core0_Linkloop10core0_Link")
link_loop10core0_Link.connect( (comp_nic10core0_EmberEP, "loop", "1000ps"), (comp_loopBack10, "core0", "1000ps") )
link_link_g0r2h3 = sst.Link("link_link_g0r2h3link_g0r2h3")
link_link_g0r2h3.connect( (comp_rtr_G0R2, "port3", "40000ps"), (comp_nic11, "rtr", "40000ps") )
link_nic11core0_Link = sst.Link("link_nic11core0_Linknic11core0_Link")
link_nic11core0_Link.connect( (comp_nic11core0_EmberEP, "nic", "150000ps"), (comp_nic11, "core0", "150000ps") )
link_loop11core0_Link = sst.Link("link_loop11core0_Linkloop11core0_Link")
link_loop11core0_Link.connect( (comp_nic11core0_EmberEP, "loop", "1000ps"), (comp_loopBack11, "core0", "1000ps") )
link_link_g1r0h0 = sst.Link("link_link_g1r0h0link_g1r0h0")
link_link_g1r0h0.connect( (comp_rtr_G1R0, "port0", "40000ps"), (comp_nic12, "rtr", "40000ps") )
link_nic12core0_Link = sst.Link("link_nic12core0_Linknic12core0_Link")
link_nic12core0_Link.connect( (comp_nic12core0_EmberEP, "nic", "150000ps"), (comp_nic12, "core0", "150000ps") )
link_loop12core0_Link = sst.Link("link_loop12core0_Linkloop12core0_Link")
link_loop12core0_Link.connect( (comp_nic12core0_EmberEP, "loop", "1000ps"), (comp_loopBack12, "core0", "1000ps") )
link_link_g1r0h1 = sst.Link("link_link_g1r0h1link_g1r0h1")
link_link_g1r0h1.connect( (comp_rtr_G1R0, "port1", "40000ps"), (comp_nic13, "rtr", "40000ps") )
link_nic13core0_Link = sst.Link("link_nic13core0_Linknic13core0_Link")
link_nic13core0_Link.connect( (comp_nic13core0_EmberEP, "nic", "150000ps"), (comp_nic13, "core0", "150000ps") )
link_loop13core0_Link = sst.Link("link_loop13core0_Linkloop13core0_Link")
link_loop13core0_Link.connect( (comp_nic13core0_EmberEP, "loop", "1000ps"), (comp_loopBack13, "core0", "1000ps") )
link_link_g1r0h2 = sst.Link("link_link_g1r0h2link_g1r0h2")
link_link_g1r0h2.connect( (comp_rtr_G1R0, "port2", "40000ps"), (comp_nic14, "rtr", "40000ps") )
link_nic14core0_Link = sst.Link("link_nic14core0_Linknic14core0_Link")
link_nic14core0_Link.connect( (comp_nic14core0_EmberEP, "nic", "150000ps"), (comp_nic14, "core0", "150000ps") )
link_loop14core0_Link = sst.Link("link_loop14core0_Linkloop14core0_Link")
link_loop14core0_Link.connect( (comp_nic14core0_EmberEP, "loop", "1000ps"), (comp_loopBack14, "core0", "1000ps") )
link_link_g1r0h3 = sst.Link("link_link_g1r0h3link_g1r0h3")
link_link_g1r0h3.connect( (comp_rtr_G1R0, "port3", "40000ps"), (comp_nic15, "rtr", "40000ps") )
link_nic15core0_Link = sst.Link("link_nic15core0_Linknic15core0_Link")
link_nic15core0_Link.connect( (comp_nic15core0_EmberEP, "nic", "150000ps"), (comp_nic15, "core0", "150000ps") )
link_loop15core0_Link = sst.Link("link_loop15core0_Linkloop15core0_Link")
link_loop15core0_Link.connect( (comp_nic15core0_EmberEP, "loop", "1000ps"), (comp_loopBack15, "core0", "1000ps") )
link_link_g1r0r1 = sst.Link("link_link_g1r0r1link_g1r0r1")
link_link_g1r0r1.connect( (comp_rtr_G1R0, "port4", "40000ps"), (comp_rtr_G1R1, "port4", "40000ps") )
link_link_g1r0r2 = sst.Link("link_link_g1r0r2link_g1r0r2")
link_link_g1r0r2.connect( (comp_rtr_G1R0, "port5", "40000ps"), (comp_rtr_G1R2, "port4", "40000ps") )
link_link_g1r1h0 = sst.Link("link_link_g1r1h0link_g1r1h0")
link_link_g1r1h0.connect( (comp_rtr_G1R1, "port0", "40000ps"), (comp_nic16, "rtr", "40000ps") )
link_nic16core0_Link = sst.Link("link_nic16core0_Linknic16core0_Link")
link_nic16core0_Link.connect( (comp_nic16core0_EmberEP, "nic", "150000ps"), (comp_nic16, "core0", "150000ps") )
link_loop16core0_Link = sst.Link("link_loop16core0_Linkloop16core0_Link")
link_loop16core0_Link.connect( (comp_nic16core0_EmberEP, "loop", "1000ps"), (comp_loopBack16, "core0", "1000ps") )
link_link_g1r1h1 = sst.Link("link_link_g1r1h1link_g1r1h1")
link_link_g1r1h1.connect( (comp_rtr_G1R1, "port1", "40000ps"), (comp_nic17, "rtr", "40000ps") )
link_nic17core0_Link = sst.Link("link_nic17core0_Linknic17core0_Link")
link_nic17core0_Link.connect( (comp_nic17core0_EmberEP, "nic", "150000ps"), (comp_nic17, "core0", "150000ps") )
link_loop17core0_Link = sst.Link("link_loop17core0_Linkloop17core0_Link")
link_loop17core0_Link.connect( (comp_nic17core0_EmberEP, "loop", "1000ps"), (comp_loopBack17, "core0", "1000ps") )
link_link_g1r1h2 = sst.Link("link_link_g1r1h2link_g1r1h2")
link_link_g1r1h2.connect( (comp_rtr_G1R1, "port2", "40000ps"), (comp_nic18, "rtr", "40000ps") )
link_nic18core0_Link = sst.Link("link_nic18core0_Linknic18core0_Link")
link_nic18core0_Link.connect( (comp_nic18core0_EmberEP, "nic", "150000ps"), (comp_nic18, "core0", "150000ps") )
link_loop18core0_Link = sst.Link("link_loop18core0_Linkloop18core0_Link")
link_loop18core0_Link.connect( (comp_nic18core0_EmberEP, "loop", "1000ps"), (comp_loopBack18, "core0", "1000ps") )
link_link_g1r1h3 = sst.Link("link_link_g1r1h3link_g1r1h3")
link_link_g1r1h3.connect( (comp_rtr_G1R1, "port3", "40000ps"), (comp_nic19, "rtr", "40000ps") )
link_nic19core0_Link = sst.Link("link_nic19core0_Linknic19core0_Link")
link_nic19core0_Link.connect( (comp_nic19core0_EmberEP, "nic", "150000ps"), (comp_nic19, "core0", "150000ps") )
link_loop19core0_Link = sst.Link("link_loop19core0_Linkloop19core0_Link")
link_loop19core0_Link.connect( (comp_nic19core0_EmberEP, "loop", "1000ps"), (comp_loopBack19, "core0", "1000ps") )
link_link_g1r1r2 = sst.Link("link_link_g1r1r2link_g1r1r2")
link_link_g1r1r2.connect( (comp_rtr_G1R1, "port5", "40000ps"), (comp_rtr_G1R2, "port5", "40000ps") )
link_link_g1r2h0 = sst.Link("link_link_g1r2h0link_g1r2h0")
link_link_g1r2h0.connect( (comp_rtr_G1R2, "port0", "40000ps"), (comp_nic20, "rtr", "40000ps") )
link_nic20core0_Link = sst.Link("link_nic20core0_Linknic20core0_Link")
link_nic20core0_Link.connect( (comp_nic20core0_EmberEP, "nic", "150000ps"), (comp_nic20, "core0", "150000ps") )
link_loop20core0_Link = sst.Link("link_loop20core0_Linkloop20core0_Link")
link_loop20core0_Link.connect( (comp_nic20core0_EmberEP, "loop", "1000ps"), (comp_loopBack20, "core0", "1000ps") )
link_link_g1r2h1 = sst.Link("link_link_g1r2h1link_g1r2h1")
link_link_g1r2h1.connect( (comp_rtr_G1R2, "port1", "40000ps"), (comp_nic21, "rtr", "40000ps") )
link_nic21core0_Link = sst.Link("link_nic21core0_Linknic21core0_Link")
link_nic21core0_Link.connect( (comp_nic21core0_EmberEP, "nic", "150000ps"), (comp_nic21, "core0", "150000ps") )
link_loop21core0_Link = sst.Link("link_loop21core0_Linkloop21core0_Link")
link_loop21core0_Link.connect( (comp_nic21core0_EmberEP, "loop", "1000ps"), (comp_loopBack21, "core0", "1000ps") )
link_link_g1r2h2 = sst.Link("link_link_g1r2h2link_g1r2h2")
link_link_g1r2h2.connect( (comp_rtr_G1R2, "port2", "40000ps"), (comp_nic22, "rtr", "40000ps") )
link_nic22core0_Link = sst.Link("link_nic22core0_Linknic22core0_Link")
link_nic22core0_Link.connect( (comp_nic22core0_EmberEP, "nic", "150000ps"), (comp_nic22, "core0", "150000ps") )
link_loop22core0_Link = sst.Link("link_loop22core0_Linkloop22core0_Link")
link_loop22core0_Link.connect( (comp_nic22core0_EmberEP, "loop", "1000ps"), (comp_loopBack22, "core0", "1000ps") )
link_link_g1r2h3 = sst.Link("link_link_g1r2h3link_g1r2h3")
link_link_g1r2h3.connect( (comp_rtr_G1R2, "port3", "40000ps"), (comp_nic23, "rtr", "40000ps") )
link_nic23core0_Link = sst.Link("link_nic23core0_Linknic23core0_Link")
link_nic23core0_Link.connect( (comp_nic23core0_EmberEP, "nic", "150000ps"), (comp_nic23, "core0", "150000ps") )
link_loop23core0_Link = sst.Link("link_loop23core0_Linkloop23core0_Link")
link_loop23core0_Link.connect( (comp_nic23core0_EmberEP, "loop", "1000ps"), (comp_loopBack23, "core0", "1000ps") )
# End of generated output.

