.TH "cp_socket" 3 "MARCH 2006" "libcprops" "cp_client"
.SH NAME
cp_client_destroy \- deallocate a tcp client structure
.SH SYNOPSIS
#include <cprops/client.h>

.BI "void cp_client_destroy(cp_client *" client ");
.SH DESCRIPTION
.B cp_client_destroy
deallocates the memory associated with a 
.B cp_client
structure. 
