.TH cp_heap 3 "JULY 2006" libcprops.0.1.5 "libcprops - cp_heap"
.SH NAME
cp_heap_count \- return the number of items stored in a heap

.SH SYNOPSIS
#include <cprops/heap.h>

.BI "int cp_heap_count(cp_heap *" heap ");

.SH DESCRIPTION
cp_heap_count returns the number of items currently stored in a heap.
