.TH cp_hashtable 3 "OCTOBER 2005" libcprops.0.0.3 "libcprops - cp_hashtable"
.SH NAME
cp_hashtable_contains \- test a hashtable for the existence of a mapping
.SH SYNOPSIS
.B #include <cprops/hashtable.h>

.BI "int cp_hashtable_contains(cp_hashtable *" table ", void *" key ");
.SH DESCRIPTION
\fBcp_hashtable_contains\fP tests if the hashtable \fItable\fP contains a 
mapping for the key \fIkey\fP. 
.SH RETURN VALUE
non-zero if a mapping for \fIkey\fP is found, zero if not.
.SH "SEE ALSO"
.BR cp_hashtable_get (3)
