.TH cp_hashtable 3 "OCTOBER 2005" libcprops.0.0.3 "libcprops - cp_hashtable"
.SH NAME
cp_hashtable_is_empty \- test if a hashtable is empty
.SH SYNOPSIS
.B #include <cprops/hashtable.h>

.BI "cp_hashtable_is_empty(cp_hashtable *" table ");
.SH DESCRIPTION
\fBcp_hashtable_is_empty\fP tests if a hashtable is empty.
.SH RETURN VALUE
non-zero if the hashtable is empty, zero if it is.
.SH "SEE ALSO"
.BR cp_hashtable_count (3)
