.TH cp_hashlist 3 "OCTOBER 2005" libcprops.0.0.3 "libcprops - cp_hashlist"
.SH NAME
cp_hashlist_is_empty \- test if a hashlist is empty
.SH SYNOPSIS
.B #include <cprops/hashlist.h>

.BI "cp_hashlist_is_empty(cp_hashlist *" table ");
.SH DESCRIPTION
\fBcp_hashlist_is_empty\fP tests if a hashlist is empty.
.SH RETURN VALUE
non-zero if the hashlist is empty, zero if it is.
.SH "SEE ALSO"
.BR cp_hashlist_count (3)
