.TH cp_hashlist 3 "OCTOBER 2005" libcprops.0.0.3 "libcprops - cp_hashlist"
.SH NAME
cp_hashlist_count \- hashlist item count
.SH SYNOPSIS
.B #include <cprops/hashlist.h>

.BI "unsigned long cp_hashlist_item_count(cp_hashlist *" list ");
.SH DESCRIPTION
\fBcp_hashlist_count\fP returns the number of mappings in a hashlist.
.SH RETURN VALUE
the number of mappings in the hashlist as a long integer.
.SH SEE ALSO
cp_hashlist_is_empty (3)
