.TH cp_hashtable 3 "OCTOBER 2005" libcprops.0.0.3 "libcprops - cp_hashtable"
.SH NAME
cp_hashtable_count \- hashtable item count
.SH SYNOPSIS
.B #include <cprops/hashtable.h>

.BI "unsigned long cp_hashtable_count(cp_hashtable *" table ");
.SH DESCRIPTION
\fBcp_hashtable_count\fP returns the number of mappings in a hashtable.
.SH RETURN VALUE
the number of mappings in the hashtable as an unsigned long integer.
.SH SEE ALSO
cp_hashtable_is_empty (3)
