.TH cp_mempool 3 "SEPTEMBER 2006" libcprops.0.1.6 "libcprops - cp_mempool"
.SH NAME
cp_mempool_inc_refcount \- increase the reference count on a memory pool

.SH SYNOPSIS 
#include <cprops/mempool.h>
.sp
.BI "int cp_mempool_inc_refcount(cp_mempool *" pool ");

.SH DESCRIPTION
.B cp_mempool_inc_refcount
increases the reference count on a memory pool. This is used internally by 
.BR cp_shared_mempool (3)
to coordinate the sharing of a memory pool between otherwise uncoordinated 
clients. 

.SH RETURN VALUE
zero on success or non-zero on locking failure if
.B COLLECTION_MODE_NOSYNC
is not set.

.SH SEE ALSO
.BR cp_mempool_create (3),
.BR cp_mempool_alloc (3), 
.BR cp_mempool_free (3), 
.BR cp_mempool_destroy (3),
.BR cp_shared_mempool (3)
