.TH cp_multimap 3 "OCT 2007" libcprops.0.1.7 "libcprops - cp_multimap"
.SH NAME
cp_multimap_get, cp_multimap_get_by_index, cp_multimap_find, cp_multimap_find_by_index \- retrieve entries from a multimap

.SH SYNOPSIS
#include <cprops/multimap.h>
.sp
.BI "void *cp_multimap_get(cp_multimap *" tree ", void *" entry ");
.br
.BI "void *cp_multimap_get_by_index(cp_multimap *" map ", 
.ti +31n
.BI "cp_index *" index ", 
.ti +31n
.BI "void *" entry ");
.sp
.BI "void *cp_multimap_find(cp_multimap *" map ", void *" key ", cp_op " op ");
.br
.BI "void *cp_multimap_find_by_index(cp_multimap *" map ", 
.ti +32n
.BI "cp_index *" index ", 
.ti +32n
.BI "void *" entry ", 
.ti +32n
.BI "cp_op " op ");

.SH DESCRIPTION
.B cp_multimap_get
returns the requested entry using the primary index.
.B cp_multimap_get_by_index
allows specifying a different index. The functions
.B cp_multimap_find
and
.B cp_multimap_find_by_index
allow lookups for entries by relational operator - the 
.B op
parameter may be one of the following: 
.sp
\fBCP_OP_LT\fP - returns an entry less than the given key
.br
\fBCP_OP_LE\fP - returns an entry less than or equal to the given key
.br
\fBCP_OP_EQ\fP - returns an entry equals to the given key - this is the same as cp_multimap_get
.br
\fBCP_OP_NE\fP - returns an entry not equal to the given key
.br
\fBCP_OP_GE\fP - returns an entry greater or equals to the given key
.br
\fBCP_OP_GT\fP - returns an entry greater than the given key
.sp
If the index used for the retrieval operation is non-unique, matches are \
returned in a 
.B cp_vector
object. The number of matches returned may be determined by calling 
.B cp_vector_size
on the result, which will be a number equal or greater to one. 
.sp
.SH RETURN VALUE
All functions return NULL if no match was found, or the item matched. For 
non-unique keys, one or more matches are wrapped in a 
.B cp_vector
object. 
.SH SEE ALSO
.BR cp_multimap_contains (3), 
.BR cp_vector (3)
