.TH cp_multimap 3 "OCT 2007" libcprops.0.1.7 "libcprops - cp_multimap"
.SH NAME
cp_multimap_count, cp_multimap_size \- return the number of items in a multimap

.SH SYNOPSIS
#include <cprops/multimap.h>
.sp
.BI "int cp_multimap_count(cp_multimap *" tree ");

.SH DESCRIPTION
.B cp_multimap_count
returns the number of items in a multi-map. 
.B cp_multimap_size
is a synonym for \fBcp_multimap_count\fP.
