.TH "cp_string" 3 "MARCH 2006" "libcprops" "cp_string"
.SH NAME
cp_string_cstrcpy \- copy a null terminated string to a cp_string
.SH SYNOPSIS
#include <cprops/str.h>

.BI "cp_string *cp_string_cstrcpy(cp_string *" dst ", char *" src ");
.SH DESCRIPTION
.B cp_string_cstrcpy
copies the null terminated string pointed at by 
.I src
onto \fIdst\fP. If necessary the internal buffer of the destination string is 
reallocated to accomodate for the source string including the terminating null.

.SH RETURN VALUE
the 
.I dst
parameter on success or 
.B NULL
on failure. 
.SH SEE ALSO
.BR cp_string_cpy (3),
.BR cp_string_cstrdup (3)
