.TH "cp_string" 3 "MARCH 2006" "libcprops" "cp_string"
.SH NAME
cp_string_cat_bin \- concatenate a buffer to a cp_string
.SH SYNOPSIS
#include <cprops/str.h>

.BI "cp_string *cp_string_cat(cp_string *" str ", void *" bin ", int " len ");
.SH DESCRIPTION
.B cp_string_cat
copies 
.I len 
bytes from 
.I bin
to the end of 
\fIdst\fP.
.SH RETURN VALUE
the 
.I dst
parameter on success or 
.B NULL
on failure. 
.SH SEE ALSO
.BR cp_string_cat (3), 
.BR cp_string_cstrcat (3)
