.TH "cp_string" 3 "MARCH 2006" "libcprops" "cp_string"
.SH NAME
cp_string_dump \- write a hex dump of a cp_string
.SH SYNOPSIS
#include <cprops/str.h>

.BI "void cp_string_dump(cp_string *" str ");
.SH DESCRIPTION
.B cp_string_dump
writes a hex dump of the given string
.I str
to the standard output.
