.TH cp_vector 3 "MARCH 2006" libcprops-0.0.12 "libcprops - cp_vector"
.SH NAME
cp_vector_size \- return the length of a vector
.SH SYNOPSIS
#include <cprops/vector.h>

.BI "int cp_vector_size(cp_vector *" vector ");
.SH DESCRIPTION
.B cp_vector_size
returns the current length of the given \fIvector\fP.
